//! Wrye Bash Plugin Checker Report Parser
//!
//! Parses ModChecker.html reports generated by Wrye Bash's Plugin Checker feature.
//! Extracts plugin issues, ESL-capable plugins, and other warnings from the HTML report,
//! then formats them into human-readable diagnostic messages.
//!
//! Replaces Python `ClassicLib.scanning.game.wrye_check` with native Rust implementation
//! using the `scraper` crate (equivalent to Python's BeautifulSoup).
//!
//! ## Usage
//!
//! ```rust,no_run
//! use classic_scangame_core::wrye::WryeBashParser;
//! use std::collections::HashMap;
//!
//! let html = std::fs::read_to_string("ModChecker.html").unwrap();
//! let warnings = HashMap::new();
//! let parser = WryeBashParser::new(warnings);
//! let issues = parser.parse(&html);
//! let report = WryeBashParser::format_report(&issues);
//! println!("{}", report);
//! ```

use std::collections::HashMap;

use scraper::{ElementRef, Html, Selector};
use thiserror::Error;

/// Errors that can occur during Wrye Bash report parsing
#[derive(Debug, Error)]
pub enum WryeError {
    /// HTML parsing encountered an issue
    #[error("HTML parsing error: {0}")]
    ParseError(String),
}

/// Result type for Wrye operations
pub type Result<T> = std::result::Result<T, WryeError>;

/// Severity level for Wrye Bash issues
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WryeSeverity {
    /// Informational notice
    Info,
    /// Warning requiring attention
    Warning,
    /// Error requiring immediate action
    Error,
}

/// An issue found in the Wrye Bash plugin checker report
#[derive(Debug, Clone)]
pub struct WryeIssue {
    /// Section title from the report (e.g., "Missing Masters", "ESL Capable")
    pub section_title: String,

    /// Plugin names associated with this section
    pub plugins: Vec<String>,

    /// Warning message from the YAML database, if any
    pub warning_message: Option<String>,

    /// Issue severity
    pub severity: WryeSeverity,
}

/// Parser for Wrye Bash ModChecker.html reports
///
/// Extracts sections (h3 headers) and their associated plugin lists from
/// the HTML report. Matches sections against a warnings dictionary loaded
/// from the YAML database.
///
/// # Example
///
/// ```rust
/// use classic_scangame_core::wrye::WryeBashParser;
/// use std::collections::HashMap;
///
/// let mut warnings = HashMap::new();
/// warnings.insert("Missing Masters".to_string(), "  Some masters are missing!\n".to_string());
///
/// let parser = WryeBashParser::new(warnings);
/// let html = "<html><body><h3>Missing Masters</h3><p>• MyMod.esp</p></body></html>";
/// let issues = parser.parse(html);
/// assert_eq!(issues.len(), 1);
/// assert_eq!(issues[0].plugins.len(), 1);
/// ```
pub struct WryeBashParser {
    /// Warning messages keyed by section title substring
    wrye_warnings: HashMap<String, String>,
}

impl WryeBashParser {
    /// Create a new parser with the given warning messages
    ///
    /// # Arguments
    ///
    /// * `wrye_warnings` - Map of warning name substrings to warning message text.
    ///   When a section title contains a key from this map, the corresponding message
    ///   is attached to the issue.
    pub fn new(wrye_warnings: HashMap<String, String>) -> Self {
        Self { wrye_warnings }
    }

    /// Parse an HTML Wrye Bash report and extract issues
    ///
    /// Processes each `<h3>` section in the HTML document, extracts plugin names
    /// from subsequent `<p>` elements, and matches sections against known warnings.
    ///
    /// # Arguments
    ///
    /// * `html_content` - Raw HTML string from ModChecker.html
    ///
    /// # Returns
    ///
    /// Vector of `WryeIssue` structs, one per section found (excluding "Active Plugins:")
    pub fn parse(&self, html_content: &str) -> Vec<WryeIssue> {
        let document = Html::parse_document(html_content);
        let h3_selector = Selector::parse("h3").expect("valid h3 selector");

        let mut issues = Vec::new();

        for h3_element in document.select(&h3_selector) {
            let title = h3_element.text().collect::<String>();

            // Skip the "Active Plugins:" section entirely (matches Python behavior)
            if title == "Active Plugins:" {
                continue;
            }

            let plugins = Self::extract_plugins_from_section(&h3_element);

            // Find matching warnings from the database
            let warning_message = self
                .wrye_warnings
                .iter()
                .find(|(warning_name, _)| title.contains(warning_name.as_str()))
                .map(|(_, text)| text.clone());

            // Determine severity based on section content
            let severity = if title == "ESL Capable" {
                WryeSeverity::Info
            } else if warning_message.is_some() {
                WryeSeverity::Warning
            } else {
                WryeSeverity::Info
            };

            issues.push(WryeIssue {
                section_title: title,
                plugins,
                warning_message,
                severity,
            });
        }

        issues
    }

    /// Extract plugin names from paragraphs following an h3 section
    ///
    /// Walks sibling `<p>` elements after the given `<h3>` and collects text that
    /// contains plugin file extensions (.esp, .esl, .esm). Stops when encountering
    /// a `<p>` that belongs to a different `<h3>` section.
    fn extract_plugins_from_section(section: &ElementRef<'_>) -> Vec<String> {
        let mut plugins = Vec::new();

        // Walk next siblings looking for <p> elements
        let mut sibling = section.next_sibling();
        while let Some(node) = sibling {
            // If we encounter another h3, stop - we've left our section
            if let Some(elem) = ElementRef::wrap(node) {
                if elem.value().name() == "h3" {
                    break;
                }

                if elem.value().name() == "p" {
                    let text = elem
                        .text()
                        .collect::<String>()
                        .trim()
                        .replace("•\u{a0} ", "");

                    if text.contains(".esp") || text.contains(".esl") || text.contains(".esm") {
                        plugins.push(text);
                    }
                }
            }

            sibling = node.next_sibling();
        }

        plugins
    }

    /// Format a section header with centered title (matching Python output)
    ///
    /// If the title is shorter than 32 characters, it gets padded with `=` signs
    /// on both sides for visual distinction.
    fn format_section_header(title: &str) -> String {
        if title.len() < 32 {
            let diff = 32 - title.len();
            let left = diff / 2;
            let right = diff - left;
            format!(
                "\n   {} {} {}\n",
                "=".repeat(left),
                title,
                "=".repeat(right)
            )
        } else {
            title.to_string()
        }
    }

    /// Format parsed issues into a complete report string
    ///
    /// Produces output matching the Python `parse_wrye_report()` function format,
    /// including section headers, ESL guidance, warning messages, and plugin lists.
    ///
    /// # Arguments
    ///
    /// * `issues` - Slice of `WryeIssue` structs from `parse()`
    ///
    /// # Returns
    ///
    /// Formatted report string ready for display
    pub fn format_report(issues: &[WryeIssue]) -> String {
        let mut parts = Vec::new();

        for issue in issues {
            // Section header
            parts.push(Self::format_section_header(&issue.section_title));

            // Special ESL Capable section
            if issue.section_title == "ESL Capable" {
                parts.push(format!(
                    "❓ There are {} plugins that can be given the ESL flag. This can be done with\n",
                    issue.plugins.len()
                ));
                parts.push(
                    "  the SimpleESLify script to avoid reaching the plugin limit (254 esm/esp).\n"
                        .to_string(),
                );
                parts.push(
                    "  SimpleESLify: https://www.nexusmods.com/skyrimspecialedition/mods/27568\n  -----\n"
                        .to_string(),
                );
            }

            // Warning message from database
            if let Some(ref warning) = issue.warning_message {
                parts.push(warning.clone());
            }

            // Plugin list (skip for ESL Capable section - matches Python behavior)
            if issue.section_title != "ESL Capable" {
                for plugin in &issue.plugins {
                    parts.push(format!("    > {plugin}\n"));
                }
            }
        }

        parts.join("")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a minimal but realistic Wrye Bash HTML report for testing
    fn sample_html() -> &'static str {
        r#"<html><body>
        <h3>Missing Masters</h3>
        <p>•&nbsp; ArmorKeywords.esm</p>
        <p>•&nbsp; AWKCR.esp</p>
        <h3>ESL Capable</h3>
        <p>•&nbsp; SmallMod.esp</p>
        <p>•&nbsp; TinyPatch.esl</p>
        <h3>Active Plugins:</h3>
        <p>•&nbsp; Fallout4.esm</p>
        <p>•&nbsp; DLCCoast.esm</p>
        <h3>Delinquent Masters</h3>
        <p>•&nbsp; OldMod.esp</p>
        <p>Some non-plugin text that should be ignored</p>
        </body></html>"#
    }

    #[test]
    fn test_parse_extracts_sections() {
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse(sample_html());

        // Should have 3 sections (Active Plugins is skipped)
        assert_eq!(issues.len(), 3);
        assert_eq!(issues[0].section_title, "Missing Masters");
        assert_eq!(issues[1].section_title, "ESL Capable");
        assert_eq!(issues[2].section_title, "Delinquent Masters");
    }

    #[test]
    fn test_parse_extracts_plugins() {
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse(sample_html());

        // Missing Masters should have 2 plugins
        assert_eq!(issues[0].plugins.len(), 2);
        assert!(issues[0].plugins[0].contains("ArmorKeywords.esm"));
        assert!(issues[0].plugins[1].contains("AWKCR.esp"));

        // ESL Capable should have 2 plugins
        assert_eq!(issues[1].plugins.len(), 2);

        // Delinquent Masters should have 1 plugin (non-plugin text is filtered)
        assert_eq!(issues[2].plugins.len(), 1);
        assert!(issues[2].plugins[0].contains("OldMod.esp"));
    }

    #[test]
    fn test_parse_skips_active_plugins() {
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse(sample_html());

        assert!(
            !issues.iter().any(|i| i.section_title == "Active Plugins:"),
            "Active Plugins section should be skipped"
        );
    }

    #[test]
    fn test_parse_with_warnings() {
        let mut warnings = HashMap::new();
        warnings.insert(
            "Missing Masters".to_string(),
            "  WARNING: Some masters are missing!\n".to_string(),
        );

        let parser = WryeBashParser::new(warnings);
        let issues = parser.parse(sample_html());

        assert!(issues[0].warning_message.is_some());
        assert!(
            issues[0]
                .warning_message
                .as_ref()
                .unwrap()
                .contains("missing")
        );
        // ESL Capable has no warning
        assert!(issues[1].warning_message.is_none());
    }

    #[test]
    fn test_parse_empty_html() {
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse("");

        assert!(issues.is_empty());
    }

    #[test]
    fn test_parse_malformed_html() {
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse("<html><h3>Broken");

        // scraper is lenient - should still parse the h3
        assert_eq!(issues.len(), 1);
        assert_eq!(issues[0].section_title, "Broken");
        assert!(issues[0].plugins.is_empty());
    }

    #[test]
    fn test_parse_html_no_h3() {
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse("<html><body><p>No sections here</p></body></html>");

        assert!(issues.is_empty());
    }

    #[test]
    fn test_format_section_header_short() {
        let header = WryeBashParser::format_section_header("Missing Masters");
        assert!(header.contains("="));
        assert!(header.contains("Missing Masters"));
    }

    #[test]
    fn test_format_section_header_long() {
        let long_title = "This Is A Very Long Section Title That Exceeds Thirty Two Characters";
        let header = WryeBashParser::format_section_header(long_title);
        // Long titles are returned as-is
        assert_eq!(header, long_title);
    }

    #[test]
    fn test_format_report_esl_capable() {
        let issues = vec![WryeIssue {
            section_title: "ESL Capable".to_string(),
            plugins: vec!["SmallMod.esp".to_string(), "TinyPatch.esl".to_string()],
            warning_message: None,
            severity: WryeSeverity::Info,
        }];

        let report = WryeBashParser::format_report(&issues);
        assert!(report.contains("2 plugins"));
        assert!(report.contains("SimpleESLify"));
        // ESL Capable section should NOT list individual plugins
        assert!(!report.contains("> SmallMod.esp"));
    }

    #[test]
    fn test_format_report_with_plugins() {
        let issues = vec![WryeIssue {
            section_title: "Missing Masters".to_string(),
            plugins: vec!["AWKCR.esp".to_string()],
            warning_message: Some("  Fix your load order!\n".to_string()),
            severity: WryeSeverity::Warning,
        }];

        let report = WryeBashParser::format_report(&issues);
        assert!(report.contains("Missing Masters"));
        assert!(report.contains("> AWKCR.esp"));
        assert!(report.contains("Fix your load order!"));
    }

    #[test]
    fn test_format_report_empty() {
        let report = WryeBashParser::format_report(&[]);
        assert!(report.is_empty());
    }

    #[test]
    fn test_bullet_cleanup() {
        // Verify the Unicode non-breaking space bullet prefix is stripped
        let html = "<html><body><h3>Test</h3><p>\u{2022}\u{a0} MyMod.esp</p></body></html>";
        let parser = WryeBashParser::new(HashMap::new());
        let issues = parser.parse(html);

        assert_eq!(issues.len(), 1);
        assert_eq!(issues[0].plugins.len(), 1);
        assert_eq!(issues[0].plugins[0], "MyMod.esp");
    }
}
