"""
Functional report generator using fragments.

This module provides functional versions of report generation methods
that return immutable fragments instead of mutating shared state.
"""

from __future__ import annotations

from .report_fragment import ReportFragment


class ReportGeneratorFunctional:
    """Functional version of ReportGenerator that returns fragments."""

    @staticmethod
    def generate_header(crashlog_filename: str, version: str) -> ReportFragment:
        """Generate header as a fragment."""
        return ReportFragment.from_lines([
            f"# {crashlog_filename}\n",
            f"**AUTOSCAN REPORT GENERATED BY {version}**\n\n",
            "> **FOR BEST VIEWING EXPERIENCE OPEN THIS FILE IN NOTEPAD++ OR SIMILAR**\n\n",
            "> **PLEASE READ EVERYTHING CAREFULLY AND BEWARE OF FALSE POSITIVES**\n\n",
            "---\n\n",
        ])

    @staticmethod
    def generate_error_section(
        main_error: str,
        crashgen_version: str,
        crashgen_name: str,
        is_latest: bool,
        warn_outdated: str,
    ) -> ReportFragment:
        """Generate error section as a fragment."""
        lines = [
            "### Error Information\n\n",
            f"**Main Error:** {main_error}\n\n",
            f"**Detected {crashgen_name} Version:** {crashgen_version}\n\n",
        ]

        if is_latest:
            lines.append(f"✅ *You have the latest version of {crashgen_name}!*\n\n")
        else:
            lines.append(f"⚠️ {warn_outdated}\n\n")

        return ReportFragment.from_lines(lines)

    @staticmethod
    def generate_suspect_section(found_suspects: list[str]) -> ReportFragment:
        """Generate suspect section with conditional header."""
        if not found_suspects:
            return ReportFragment.from_lines([
                "### Checking If Log Matches Any Known Crash Suspects\n\n",
                "# FOUND NO CRASH ERRORS / SUSPECTS THAT MATCH THE CURRENT DATABASE #\n",
                "Check below for mods that can cause frequent crashes and other problems.\n\n",
            ])

        lines = ["### Checking If Log Matches Any Known Crash Suspects\n\n"]
        lines.extend(found_suspects)
        lines.extend([
            "* FOR DETAILED DESCRIPTIONS AND POSSIBLE SOLUTIONS TO ANY ABOVE DETECTED CRASH SUSPECTS *\n",
            "* SEE: https://docs.google.com/document/d/17FzeIMJ256xE85XdjoPvv_Zi3C5uHeSTQh6wOZugs4c *\n\n",
        ])

        return ReportFragment.from_lines(lines)
