"""
Provides a handler to bridge TUI events with core operations for scanning crash logs
or game files.

This module defines the `TuiScanHandler` class, which facilitates integration between
text user interfaces and the scanning operations for crash logs and game files. The
handler manages asynchronous scan tasks, supports optional progress and output callbacks,
and ensures thread-safe scanning through locking mechanisms.
"""

import asyncio
import sys
from collections.abc import Callable
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))

from CLASSIC_ScanLogs import ClassicScanLogs
from ClassicLib.Constants import YAML
from ClassicLib.MessageHandler import init_message_handler
from ClassicLib.YamlSettingsCache import classic_settings, yaml_settings


class TuiScanHandler:
    """Handler for TUI-based scanning operations.

    This class manages scanning operations for crash logs and game files in a terminal user
    interface (TUI) setting. It supports asynchronous execution of scans, provides tools to
    interact with scanning progress via callbacks, and ensures thread-safe operations through
    lock mechanisms. Scans can be started, cancelled, and monitored for their running state.

    Attributes:
        output_callback (Callable[[str], None] | None): Function used to send output messages
            during scan operations.
        scanner (ClassicScanLogs | None): Instance of the crash log scanner used for scanning
            operations.
        current_task (asyncio.Task | None): The currently running task for a scan operation.
        is_scanning (bool): Indicates whether a scan is currently in progress.
    """

    def __init__(self, output_callback: Callable[[str], None] | None = None) -> None:
        """Initialize the scan handler.

        Args:
            output_callback: Function to call with output messages
        """
        self.output_callback = output_callback
        self.scanner: ClassicScanLogs | None = None
        self.current_task: asyncio.Task | None = None
        self.is_scanning = False
        self._scan_lock = asyncio.Lock()

    def set_output_callback(self, callback: Callable[[str], None]) -> None:
        """
        Sets the callback function for handling output.

        The provided callback will be called with a string parameter based on
        the output generated by the system. This is useful for customizing
        how to process or display output in the context of the application.

        Args:
            callback: A callable that takes a single string argument and returns None.
        """
        self.output_callback = callback

    def _send_output(self, message: str) -> None:
        """
        Sends a message to the output callback if the callback is defined.

        Args:
            message (str): The message to be sent to the output callback.
        """
        if self.output_callback:
            self.output_callback(message)

    async def perform_crash_scan(self, scan_folder: str | None = None, progress_callback: Callable[[float], None] | None = None) -> bool:
        """
        Performs an asynchronous crash log scan.

        This method carries out a crash log scan and generates corresponding reports.
        The scan can be customized with a specific folder. It ensures that only
        one scan occurs at a time by utilizing a lock. An optional callback can
        be provided to track the progress.

        Args:
            scan_folder: Custom folder path where the crash logs are located. If None,
                the default folder is used.
            progress_callback: A callback function that receives a float value
                representing the scan progress (1.0 indicates completion).

        Returns:
            bool: True if the scan was successful, False otherwise.
        """
        # Acquire lock to check and set scanning state atomically
        async with self._scan_lock:
            if self.is_scanning:
                self._send_output("❌ Scan already in progress")
                return False
            self.is_scanning = True

        try:
            self._send_output("🔍 Starting crash logs scan...")

            # Initialize scanner
            self.scanner = ClassicScanLogs()

            # Initialize message handler for TUI mode
            init_message_handler(parent=None, is_gui_mode=False)

            # Set custom scan folder if provided
            original_folder = None
            if scan_folder:
                scan_path = Path(scan_folder)
                if scan_path.exists() and scan_path.is_dir():
                    # Batch settings operations to minimize thread transitions
                    try:
                        # Single thread transition for both read and write
                        def batch_settings_operation() -> str:
                            orig = classic_settings(str, "Scan Folder")
                            yaml_settings(str, YAML.Settings, "Scan Folder", scan_folder)
                            return orig

                        original_folder = await asyncio.to_thread(batch_settings_operation)
                        self._send_output(f"📁 Scanning folder: {scan_folder}")
                    except (OSError, KeyError, ValueError, TypeError) as e:
                        # If settings update fails, continue with default folder
                        self._send_output(f"⚠️ Could not update scan folder setting: {e}")
                        original_folder = None
                else:
                    self._send_output(f"❌ Invalid scan folder: {scan_folder}")
                    async with self._scan_lock:
                        self.is_scanning = False
                    return False

            # Run the scan using OrchestratorCore
            from ClassicLib.ScanLog.OrchestratorCore import OrchestratorCore

            try:
                # Create orchestrator with context manager like in crashlogs_scan_async_pure
                async with OrchestratorCore(
                    self.scanner.yamldata,
                    self.scanner.crashlogs,
                    self.scanner.fcx_mode,
                    self.scanner.show_formid_values,
                    self.scanner.formid_db_exists,
                ) as orchestrator:
                    # Run FCX checks if enabled
                    if self.scanner.fcx_mode:
                        orchestrator.fcx_handler.check_fcx_mode()

                    # Process all crash logs
                    tasks = [self.scanner.process_crashlog_async(log, orchestrator) for log in self.scanner.crashlog_list]

                    # Execute all tasks
                    results = await asyncio.gather(*tasks, return_exceptions=True)

                    # Process results and write reports
                    for i, result in enumerate(results):
                        if isinstance(result, BaseException):
                            self._send_output(f"❌ Error processing {self.scanner.crashlog_list[i].name}: {result}")
                        else:
                            crashlog_file, autoscan_report, trigger_scan_failed, _local_stats = result
                            # Write report using the existing async function
                            from CLASSIC_ScanLogs import write_report_to_file_async

                            await write_report_to_file_async(crashlog_file, autoscan_report, trigger_scan_failed, self.scanner)
            finally:
                # Restore original setting after scan if we changed it
                if original_folder:
                    await asyncio.to_thread(yaml_settings, str, YAML.Settings, "SCAN Custom Path", original_folder)

            self._send_output("✅ Crash logs scan completed successfully")

            if progress_callback:
                progress_callback(1.0)

        except (OSError, ValueError, TypeError, asyncio.CancelledError, ImportError) as e:
            self._send_output(f"❌ Error during crash scan: {e!s}")
            return False
        else:
            return True
        finally:
            async with self._scan_lock:
                self.is_scanning = False
                self.current_task = None

    async def perform_game_scan(self, progress_callback: Callable[[float], None] | None = None) -> bool:
        """
        Performs a game scan asynchronously with progress reporting.

        This method initiates and runs a scan for game files using an external scanning
        utility. It ensures that only one scan can take place at a time by enforcing
        proper locking mechanisms. If a scan is already in progress, it prevents starting
        another one. The function also supports reporting the scan's progress if a
        progress callback is provided.

        Args:
            progress_callback (Callable[[float], None] | None): An optional callable function that receives
                the progress of the scan as a float (0.0 to 1.0). If provided, it will be called
                with the value of 1.0 upon successful completion of the scan.

        Returns:
            bool: True if the scan completed successfully, False otherwise.
        """
        # Acquire lock to check and set scanning state atomically
        async with self._scan_lock:
            if self.is_scanning:
                self._send_output("❌ Scan already in progress")
                return False
            self.is_scanning = True

        try:
            self._send_output("🔍 Starting game files scan...")

            # Import game scanner
            from CLASSIC_ScanGame import main as scan_game_main

            # Initialize message handler for TUI mode
            init_message_handler(parent=None, is_gui_mode=False)

            # Run the game scan
            await asyncio.to_thread(scan_game_main)

            self._send_output("✅ Game files scan completed successfully")

            if progress_callback:
                progress_callback(1.0)

        except (OSError, ValueError, TypeError, asyncio.CancelledError, ImportError) as e:
            self._send_output(f"❌ Error during game scan: {e!s}")
            return False
        else:
            return True
        finally:
            async with self._scan_lock:
                self.is_scanning = False
                self.current_task = None

    async def cancel_scan(self) -> None:
        """
        Cancels an ongoing scan operation asynchronously.

        This method ensures safe access to the scanning process using a lock, and if a
        current task is running and not completed, it cancels the task. It updates the
        state accordingly by setting the related attributes to their default values.

        Raises:
            CancelledError: Raised when the ongoing current task is cancelled mid-execution.
        """
        async with self._scan_lock:
            if self.current_task and not self.current_task.done():
                self.current_task.cancel()
                self._send_output("⚠️ Scan cancelled by user")
            self.is_scanning = False
            self.current_task = None

    def is_scan_running(self) -> bool:
        """
        Determines if a scan operation is currently active.

        This method checks the current state of the scanning process
        and returns a boolean value indicating whether a scan is in progress.
        It ensures that users are informed about the scanning status.

        Returns:
            bool: True if scanning is currently active, False otherwise.
        """
        # Note: This is a simple read, but for complete thread safety,
        # callers should use this with awareness that state might change immediately after
        return self.is_scanning
