"""Fragment-based report generator for CLASSIC.

This module provides fragment-returning versions of all report generation functions,
replacing the mutable list pattern with immutable fragment composition.
"""

from typing import TYPE_CHECKING, Any

from ClassicLib import GlobalRegistry
from ClassicLib.rust.report_rust import ReportFragment
from ClassicLib.ScanLog.scanloginfo import ClassicScanLogsInfo

if TYPE_CHECKING:
    from ClassicLib.ScanLog.scanloginfo import ClassicScanLogsInfo


class ReportGeneratorFragments:
    """Manage the generation of various sections and fragments for an autoscan report.

    This class provides methods for generating standardized report fragments,
    including headers, error sections, suspect sections, and footers. The class
    leverages input configuration data and contextual information to produce
    formatted outputs useful for identifying crash issues, errors, and other
    relevant details in autoscan reports.

    Attributes:
        yamldata (ClassicScanLogsInfo | None): Configuration data for generating the report.

    """

    def __init__(self, yamldata: "ClassicScanLogsInfo | None") -> None:
        """Initialize the instance with the given ClassicScanLogsInfo data.

        Args:
            yamldata: Instance of ClassicScanLogsInfo containing YAML data or None.

        """
        self.yamldata: ClassicScanLogsInfo | None = yamldata

    def generate_header(self, crashlog_filename: str, is_vr_log: bool = False) -> ReportFragment:
        """Generate a header section for an autoscan report.

        This method creates a formatted header for the generated report fragment,
        including the crash log filename and details about the autoscan version.
        It provides best viewing instructions and cautions the reader about the
        possibility of false positives.

        Args:
            crashlog_filename (str): Name of the crash log file to be included in the
                report header.
            is_vr_log (bool): If True, adds VR mode auto-detection indicator.

        Returns:
            ReportFragment: A report fragment object containing the formatted report
                header.

        """
        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        lines = [
            f"# {crashlog_filename}\n",
            f"**AUTOSCAN REPORT GENERATED BY {version}**\n\n",
            "> **FOR BEST VIEWING EXPERIENCE OPEN THIS FILE IN NOTEPAD++ OR SIMILAR**\n\n",
            "> **PLEASE READ EVERYTHING CAREFULLY AND BEWARE OF FALSE POSITIVES**\n\n",
        ]

        # Add VR indicator if auto-detected
        if is_vr_log:
            lines.extend([
                "> ⚠️ **VR MODE AUTO-DETECTED**: This crash log is from Fallout 4 VR\n",
                "> VR-specific settings and version comparisons are being used.\n\n",
            ])

        lines.append("---\n\n")
        return ReportFragment.from_lines(lines)

    def generate_error_section(
        self,
        main_error: str,
        crashgen_version: str,
        version_current: Any,
        version_latest: Any,
        version_latest_vr: Any,
        is_vr_log: bool = False,
    ) -> ReportFragment:
        """Generate an error section of a report indicating the current status of the Crashgen
        version and whether the version is outdated or up-to-date. This section also includes
        the main error information and relevant version statuses.

        Args:
            main_error: A string describing the primary error encountered.
            crashgen_version: A string representing the detected version of the Crashgen.
            version_current: The currently installed version of Crashgen.
            version_latest: The latest available version of Crashgen.
            version_latest_vr: The latest available version of Crashgen for VR.
            is_vr_log: Whether the log is from VR version.

        Returns:
            ReportFragment: A structured report fragment containing error and version
            information formatted as lines of text.

        """
        crashgen_name = self.yamldata.crashgen_name if self.yamldata else "Crashgen"
        lines = [
            "### Error Information\n\n",
            f"**Main Error:** {main_error}\n\n",
            f"**Detected {crashgen_name} Version:** {crashgen_version}\n\n",
        ]

        # Add version status - always show whether current or outdated
        # Use is_vr_log to determine which check to perform, falling back to global setting if not specified
        game_is_vr = is_vr_log or (GlobalRegistry.get_vr() == "VR")

        if (version_current < version_latest_vr and version_current != version_latest) or (
            not game_is_vr and version_current < version_latest
        ):
            lines.append(f"***❌ WARNING: YOUR {crashgen_name} IS OUTDATED! PLEASE UPDATE TO THE LATEST VERSION!***\n\n")
        else:
            lines.append(f"✅ *You have the latest version of {crashgen_name}!*\n\n")

        lines.append("---\n\n")

        return ReportFragment.from_lines(lines)

    @staticmethod
    def generate_suspect_section_header() -> ReportFragment:
        """Generate and returns a predefined header for the suspect section in the report.

        This method creates a ReportFragment containing lines formatted specifically for
        highlighting crash messages, errors, and suspects in a report structure.

        Returns:
            ReportFragment: A fragment of the report pre-populated with relevant lines.

        """
        return ReportFragment.from_lines([
            "### Checking for Known Crash Messages, Errors and Suspects\n\n",
        ])

    @staticmethod
    def generate_suspect_found_footer(found_suspect: bool) -> ReportFragment:
        """Generate a footer section for a report indicating whether suspects were found.

        This static method creates a footer composed of formatted lines that summarize
        if suspects were detected. It calls `ReportFragment.from_lines` to produce
        the properly structured report fragment. The text content of the footer differs
        based on whether suspects were found or not.

        Args:
            found_suspect (bool): Flag indicating if one or more suspects were detected.

        Returns:
            ReportFragment: A formatted report fragment containing the footer
            indicating the result of the suspect detection.

        """
        if found_suspect:
            return ReportFragment.from_lines([
                "* **ONE OR MORE SUSPECTS DETECTED! CHECK LOG ABOVE FOR MORE INFORMATION!** *\n\n",
                "---\n\n",
            ])
        return ReportFragment.from_lines([
            "* **NO SUSPECTS DETECTED** *\n\n",
            "---\n\n",
        ])

    @staticmethod
    def generate_settings_section_header() -> ReportFragment:
        """Generate a section header for reporting settings-related issues.

        This static method creates and returns a `ReportFragment` instance that contains
        a formatted header indicating the start of a section focused on
        settings-related issues.

        Returns:
            ReportFragment: A fragment containing the settings-related issues header.

        """
        return ReportFragment.from_lines([
            "### Checking for Settings-related Issues\n\n",
        ])

    @staticmethod
    def generate_mod_check_header(check_type: str) -> ReportFragment:
        """Generate a report fragment header for mod checks based on the provided check type.

        Args:
            check_type (str): The type of mod check to include in the header.

        Returns:
            ReportFragment: A fragment containing the formatted header lines.

        """
        return ReportFragment.from_lines([
            f"### Checking For Mods That {check_type}\n\n",
        ])

    @staticmethod
    def generate_plugin_suspect_header() -> ReportFragment:
        """Generate a header fragment for reports related to plugin-related errors.

        This static method provides a descriptive header indicating the section
        of the report that pertains to identifying and analyzing plugin-related
        errors. The header serves to improve report readability and structure,
        aiding users in quickly pinpointing relevant sections.

        Returns:
            ReportFragment: A fragment containing formatted header information with
            the required lines specifying plugin-related error checks.

        """
        return ReportFragment.from_lines([
            "### Checking for Plugin-related Errors\n\n",
        ])

    @staticmethod
    def generate_formid_section_header() -> ReportFragment:
        """Generate a section header for FormID checks.

        This static method creates a ReportFragment containing a segment of text
        used as a header for indicating the FormID checking process in a report.

        Returns:
            ReportFragment: A segment of the report containing the FormID check header.

        """
        return ReportFragment.from_lines([
            "### Checking FormIDs\n\n",
        ])

    @staticmethod
    def generate_record_section_header() -> ReportFragment:
        """Generate a section header for checking named records.

        This method returns a preformatted ReportFragment object that contains
        the section header used during the process of evaluating named records.

        Returns:
            ReportFragment: An instance of ReportFragment initialized with the
            predefined header lines.

        """
        return ReportFragment.from_lines([
            "### Checking for Named Records\n\n",
        ])

    def generate_footer(self) -> ReportFragment:
        """Generate a footer section for the report.

        The method uses the `classic_version` from `yamldata` if available; otherwise,
        it defaults to "CLASSIC". The footer includes a line stating the end of the
        report and indicates the generator version.

        Returns:
            ReportFragment: The report fragment representing the footer section.

        """
        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            "---\n\n",
            "### End of Report\n\n",
            f"Generated by {version}\n",
        ])
