"""
Fragment-based report generator for CLASSIC.

This module provides fragment-returning versions of all report generation functions,
replacing the mutable list pattern with immutable fragment composition.
"""

from typing import TYPE_CHECKING, Any

from ClassicLib import GlobalRegistry
from ClassicLib.ScanLog.ReportFragment import ReportFragment
from ClassicLib.ScanLog.ScanLogInfo import ClassicScanLogsInfo

if TYPE_CHECKING:
    from ClassicLib.ScanLog.ScanLogInfo import ClassicScanLogsInfo


class ReportGeneratorFragments:
    """Fragment-based report generator for crash log analysis."""

    def __init__(self, yamldata: "ClassicScanLogsInfo") -> None:
        """
        Initialize the report generator.

        Args:
            yamldata: Configuration data
        """
        self.yamldata: ClassicScanLogsInfo = yamldata

    def generate_header(self, crashlog_filename: str) -> ReportFragment:
        """
        Generate a standardized header for an autoscan report.

        Args:
            crashlog_filename: The name of the crash log file being processed.

        Returns:
            ReportFragment containing the header.
        """
        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            f"# {crashlog_filename}\n",
            f"**AUTOSCAN REPORT GENERATED BY {version}**\n\n",
            "> **FOR BEST VIEWING EXPERIENCE OPEN THIS FILE IN NOTEPAD++ OR SIMILAR**\n\n",
            "> **PLEASE READ EVERYTHING CAREFULLY AND BEWARE OF FALSE POSITIVES**\n\n",
            "---\n\n",
        ])

    def generate_error_section(
        self,
        main_error: str,
        crashgen_version: str,
        version_current: Any,
        version_latest: Any,
        version_latest_vr: Any,
    ) -> ReportFragment:
        """
        Generate an error section for the autoscan report.

        Args:
            main_error: The main error message to be displayed.
            crashgen_version: The version string of the crashgen component.
            version_current: The current version of the crashgen.
            version_latest: The latest available version of the crashgen.
            version_latest_vr: The latest available VR version of the crashgen.

        Returns:
            ReportFragment containing the error section.
        """
        crashgen_name = self.yamldata.crashgen_name if self.yamldata else "Crashgen"
        lines = [
            "### Error Information\n\n",
            f"**Main Error:** {main_error}\n\n",
            f"**Detected {crashgen_name} Version:** {crashgen_version}\n\n",
        ]

        # Add version status - always show whether current or outdated
        game_is_vr = GlobalRegistry.get_vr() == "VR"
        if (version_current < version_latest_vr and version_current != version_latest) or (
            not game_is_vr and version_current < version_latest
        ):
            lines.append(f"***❌ WARNING: YOUR {crashgen_name} IS OUTDATED! PLEASE UPDATE TO THE LATEST VERSION!***\n\n")
        else:
            lines.append(f"✅ *You have the latest version of {crashgen_name}!*\n\n")

        lines.append("---\n\n")

        return ReportFragment.from_lines(lines)

    @staticmethod
    def generate_suspect_section_header() -> ReportFragment:
        """
        Generate header for the suspect section.

        Returns:
            ReportFragment containing the suspect section header.
        """
        return ReportFragment.from_lines([
            "### Checking for Known Crash Messages, Errors and Suspects\n\n",
        ])

    @staticmethod
    def generate_suspect_found_footer(found_suspect: bool) -> ReportFragment:
        """
        Generate footer for suspect section based on whether suspects were found.

        Args:
            found_suspect: Whether any suspects were found.

        Returns:
            ReportFragment containing the appropriate footer.
        """
        if found_suspect:
            return ReportFragment.from_lines([
                "* **ONE OR MORE SUSPECTS DETECTED! CHECK LOG ABOVE FOR MORE INFORMATION!** *\n\n",
                "---\n\n",
            ])
        return ReportFragment.from_lines([
            "* **NO SUSPECTS DETECTED** *\n\n",
            "---\n\n",
        ])

    @staticmethod
    def generate_settings_section_header() -> ReportFragment:
        """
        Generate header for the settings section.

        Returns:
            ReportFragment containing the settings section header.
        """
        return ReportFragment.from_lines([
            "### Checking for Settings-related Issues\n\n",
        ])

    @staticmethod
    def generate_mod_check_header(check_type: str) -> ReportFragment:
        """
        Generate header for mod checking sections.

        Args:
            check_type: Type of mod check being performed.

        Returns:
            ReportFragment containing the mod check header.
        """
        return ReportFragment.from_lines([
            f"### Checking For Mods That {check_type}\n\n",
        ])

    @staticmethod
    def generate_plugin_suspect_header() -> ReportFragment:
        """
        Generate header for plugin suspect section.

        Returns:
            ReportFragment containing the plugin suspect header.
        """
        return ReportFragment.from_lines([
            "### Checking for Plugin-related Errors\n\n",
        ])

    @staticmethod
    def generate_formid_section_header() -> ReportFragment:
        """
        Generate header for FormID section.

        Returns:
            ReportFragment containing the FormID section header.
        """
        return ReportFragment.from_lines([
            "### Checking FormIDs\n\n",
        ])

    @staticmethod
    def generate_record_section_header() -> ReportFragment:
        """
        Generate header for named records section.

        Returns:
            ReportFragment containing the record section header.
        """
        return ReportFragment.from_lines([
            "### Checking for Named Records\n\n",
        ])

    def generate_footer(self) -> ReportFragment:
        """
        Generate the report footer.

        Returns:
            ReportFragment containing the footer.
        """
        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            "---\n\n",
            "### End of Report\n\n",
            f"Generated by {version}\n",
        ])
