"""Python module for typed User Settings access and explicit conflict-safe updates.
"""

# Direct-import facade over the one CLASSIC native extension. Every name is
# the canonical native object, so values and exceptions created through any
# facade are the same Python types everywhere. Keep the import list and the
# literal ``__all__`` in step with ``__init__.pyi``: validate_stubs.py and the
# Python parity resolver read both.

from _classic_native._native.classic_user_settings import (
    CrashLogScanSettings,
    FrontendPreferences,
    FrontendState,
    GameSetupSettings,
    GuiWindowGeometry,
    LegacyTuiStateImportError,
    LegacyTuiStateImportOutcome,
    LegacyTuiStateImportReceipt,
    LegacyTuiStateImportRestoreOutcome,
    TuiRememberedState,
    UpdatePreferences,
    UserSettingsCommitError,
    UserSettingsCommitOutcome,
    UserSettingsDiagnostic,
    UserSettingsFrontendTransitionOutcome,
    UserSettingsMigrationApplyOutcome,
    UserSettingsMigrationChange,
    UserSettingsMigrationDiagnostic,
    UserSettingsMigrationEndpoint,
    UserSettingsMigrationError,
    UserSettingsMigrationPlan,
    UserSettingsMigrationPlanningOutcome,
    UserSettingsMigrationReceipt,
    UserSettingsMigrationRestoreOutcome,
    UserSettingsSchemaVersion,
    UserSettingsSnapshot,
    UserSettingsUpdate,
    UserSettingsUpdateDiagnostic,
    UserSettingsUpdateField,
    UserSettingsUpdatePreview,
    WindowGeometry,
    __version__,
    import_legacy_tui_state_into_user_settings,
    open_user_settings,
    user_settings_published_defaults,
)

__all__ = [
    "CrashLogScanSettings",
    "FrontendPreferences",
    "FrontendState",
    "GameSetupSettings",
    "GuiWindowGeometry",
    "LegacyTuiStateImportError",
    "LegacyTuiStateImportOutcome",
    "LegacyTuiStateImportReceipt",
    "LegacyTuiStateImportRestoreOutcome",
    "TuiRememberedState",
    "UpdatePreferences",
    "UserSettingsCommitError",
    "UserSettingsCommitOutcome",
    "UserSettingsDiagnostic",
    "UserSettingsFrontendTransitionOutcome",
    "UserSettingsMigrationApplyOutcome",
    "UserSettingsMigrationChange",
    "UserSettingsMigrationDiagnostic",
    "UserSettingsMigrationEndpoint",
    "UserSettingsMigrationError",
    "UserSettingsMigrationPlan",
    "UserSettingsMigrationPlanningOutcome",
    "UserSettingsMigrationReceipt",
    "UserSettingsMigrationRestoreOutcome",
    "UserSettingsSchemaVersion",
    "UserSettingsSnapshot",
    "UserSettingsUpdate",
    "UserSettingsUpdateDiagnostic",
    "UserSettingsUpdateField",
    "UserSettingsUpdatePreview",
    "WindowGeometry",
    "__version__",
    "import_legacy_tui_state_into_user_settings",
    "open_user_settings",
    "user_settings_published_defaults",
]
