#include "report_writer.h"
#include "rust/cxx.h"

// CXX bridge header (generated by corrosion_add_cxxbridge)
#include "classic_cxx_bridge/files.h"

#include <fmt/core.h>
#include <string>

bool write_report(const std::string& log_path,
                  const std::vector<std::string>& report_lines) {
    // Join lines into a single report string
    std::string content;
    for (const auto& line : report_lines) {
        content += line;
        content += '\n';
    }

    // Write via Rust bridge; output path derivation lives in Rust for reuse.
    try {
        classic::files::write_autoscan_report(log_path, content);
        return true;
    } catch (const rust::Error& e) {
        fmt::print(stderr, "  Error: report write failed for {}: {}\n",
            log_path, std::string(e.what()));
        return false;
    }
}
