#include "scanner.h"
#include "progress.h"
#include "scan_run_cli.h"
#include "user_settings_action.h"

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#endif

#include "rust/cxx.h"

// CXX bridge headers (generated by corrosion_add_cxxbridge)
#include "classic_cxx_bridge/message.h"
#include "classic_cxx_bridge/registry.h"
#include "classic_cxx_bridge/runtime.h"
#include "classic_cxx_bridge/scanner.h"
#include "classic_cxx_bridge/settings.h"

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fmt/core.h>
#include <memory>
#include <string>
#include <utility>

namespace fs = std::filesystem;

// ── Data root discovery ────────────────────────────────────────────

struct DataDirs {
    std::string root;
};

/// Find the installation root containing "CLASSIC Data/".
/// Mirrors the CLASSIC Data candidate search performed by MainWindow::findDataRoot().
static DataDirs find_data_root() {
    std::error_code ec;
    fs::path exe_path = fs::current_path(ec); // fallback, overridden below

#ifdef _WIN32
    // Try getting actual exe path on Windows
    wchar_t buf[MAX_PATH];
    DWORD len = GetModuleFileNameW(nullptr, buf, MAX_PATH);
    if (len > 0 && len < MAX_PATH) {
        fs::path ep(buf);
        exe_path = ep.parent_path();
        if (fs::is_directory(exe_path / "CLASSIC Data", ec)) {
            return DataDirs{exe_path.string()};
        }
    }
#endif

    // Check: Current working directory for "CLASSIC Data/" (development / distribution)
    auto cwd = fs::current_path(ec);
    if (fs::is_directory(cwd / "CLASSIC Data", ec)) {
        return DataDirs{cwd.string()};
    }

    // Check: Exe directory for "CLASSIC Data/" (running from build dir)
    if (fs::is_directory(exe_path / "CLASSIC Data", ec)) {
        return DataDirs{exe_path.string()};
    }

    // Fallback: use cwd anyway (will fail at config load with a clear error)
    return DataDirs{cwd.string()};
}

// ── Filename extraction helper ─────────────────────────────────────

static std::string filename_from_path(const std::string& path) {
    auto pos = path.find_last_of("/\\");
    return (pos != std::string::npos) ? path.substr(pos + 1) : path;
}

static std::string rust_string_to_std(const rust::String& value) {
    return std::string(value.data(), value.size());
}

static std::string startup_correlation_id() {
    char* env_value = nullptr;
    size_t env_len = 0;
    if (_dupenv_s(&env_value, &env_len, "CLASSIC_CORRELATION_ID") != 0 || env_value == nullptr) {
        return {};
    }

    std::string correlation_id(env_value);
    free(env_value);
    if (correlation_id.empty()) {
        return {};
    }
    return correlation_id;
}

/// Writes one durable presentation line to its requested console channel.
static void print_cli_scan_message(const CliScanRunMessage& message) {
    if (message.error) {
        fmt::print(stderr, "{}\n", message.text);
    } else {
        fmt::print("{}\n", message.text);
    }
}

/// Presents serialized final-contract events and translates adapter failures into safe cancellation.
class CliScanRunObserver final : public classic::scanner::ScanRunObserver {
public:
    /// Borrows the cancellation owner for the synchronous execution lifetime.
    CliScanRunObserver(std::string game, CliScanRunCancellation& cancellation)
        : game_(std::move(game))
        , cancellation_(cancellation) {}

    /// Renders one event without allowing presentation failures to cross CXX.
    void on_scan_run_event(const classic::scanner::ScanRunContractEvent& event) const noexcept override {
        try {
            if (event.kind == classic::scanner::ScanRunContractEventKind::DiscoveryCompleted) {
                progress_ = std::make_unique<ProgressDisplay>(
                    static_cast<uint32_t>(event.discovery.accepted_logs.size()), game_);
            }

            if (progress_) {
                // Clear the prior dynamic frame before printing durable event text so the next
                // render does not erase discovery, concurrency, or per-log messages.
                progress_->finish();
            }
            for (const auto& message : describe_cli_scan_run_event(event)) {
                print_cli_scan_message(message);
            }

            if (!progress_) {
                return;
            }

            const std::string key = std::to_string(event.discovery_index);
            switch (event.kind) {
            case classic::scanner::ScanRunContractEventKind::LogStarted:
                progress_->report_started(key, filename_from_path(rust_string_to_std(event.crash_log)));
                break;
            case classic::scanner::ScanRunContractEventKind::LogFinished:
                if (event.disposition == classic::scanner::ScanRunContractLogDisposition::Failed) {
                    progress_->report_error(key);
                } else {
                    progress_->report_finished(key);
                }
                break;
            case classic::scanner::ScanRunContractEventKind::DiscoveryCompleted:
            case classic::scanner::ScanRunContractEventKind::EffectiveConcurrencySelected:
            case classic::scanner::ScanRunContractEventKind::LogQueued:
            case classic::scanner::ScanRunContractEventKind::LogPhase:
                break;
            }
            progress_->render();
        } catch (...) {
            delivery_failed_ = true;
            cancellation_.request();
        }
    }

    /// Clears any live progress rendering after synchronous execution returns.
    void finish() const {
        if (progress_) {
            progress_->finish();
        }
    }

    /// Reports whether event presentation failed and requested safe cancellation.
    [[nodiscard]] bool delivery_failed() const noexcept { return delivery_failed_; }

private:
    std::string game_;
    CliScanRunCancellation& cancellation_;
    mutable std::unique_ptr<ProgressDisplay> progress_;
    mutable bool delivery_failed_ = false;
};

// ── Scan pipeline (inner) ──────────────────────────────────────────
// Factored out so rust::Box<T> objects can be constructed in-place
// rather than pre-declared (rust::Box is non-nullable, no nullptr init).

/// Projects User Settings, runs the single Rust-owned operation, and presents its typed outcome.
static int run_scan_pipeline(const CliArgs& args, const DataDirs& dirs,
                             std::chrono::steady_clock::time_point total_start) {
    const auto prepared = prepare_scan_user_settings(args, dirs.root);
    if (!prepared.has_value()) {
        return 1;
    }

    classic::registry::registry_set_game(prepared->game);
    std::string mode_suffix;
    if (prepared->game_version != "auto") {
        mode_suffix += " " + prepared->game_version;
    }
    if (prepared->fcx_mode) {
        mode_suffix += " [FCX]";
    }
    fmt::print("CLASSIC v{} - Crash Log Scanner ({}{})\n\n", CLASSIC_CLI_VERSION, prepared->game, mode_suffix);

    std::error_code ec;
    const std::string base_dir = fs::current_path(ec).string();
    const auto request = build_cli_scan_run_request(args, *prepared, dirs.root, base_dir);
    CliScanRunCancellation cancellation;
    CliScanRunObserver observer(prepared->game, cancellation);
    const auto execution = classic::scanner::scan_run_contract_execute(*request, cancellation.token(), &observer);
    observer.finish();

    if (observer.delivery_failed()) {
        fmt::print(stderr, "Warning: scan progress presentation failed; safe cancellation was requested.\n");
    }

    const auto total_end = std::chrono::steady_clock::now();
    const double duration = std::chrono::duration<double>(total_end - total_start).count();
    const auto presentation = present_cli_scan_run_execution(execution, duration);
    fmt::print("\n");
    for (const auto& message : presentation.messages) {
        print_cli_scan_message(message);
    }
    return presentation.exit_code;
}

// ── Public entry point ─────────────────────────────────────────────

int run_scan(const CliArgs& args) {
    auto total_start = std::chrono::steady_clock::now();
    const std::string correlation_id = startup_correlation_id();

    // Initialize Rust runtime + logging
    try {
        classic::message::init_logging();
        classic::runtime::init_runtime();
        classic::message::log_startup_binding_contract_validated("classic-cli.startup", 3, correlation_id);
        classic::message::log_startup_acceleration_status(1, 1, "MANDATORY", correlation_id);
    } catch (const rust::Error& e) {
        classic::message::log_startup_binding_contract_failed(
            "classic-cli.startup", "classic::runtime::init_runtime", "runtime_init",
            "Run classic-cli/build_cli.ps1 to rebuild the C++ bridge and verify runtime dependencies.", e.what(),
            correlation_id);
        fmt::print(stderr, "Fatal: failed to initialize runtime: {}\n", std::string(e.what()));
        return 2;
    }

    // Find data root
    auto dirs = find_data_root();
    fmt::print("Data root: {}\n", dirs.root);
    fmt::print("\n");

    // Run the scan pipeline (all rust::Box<T> objects live inside this scope)
    int exit_code;
    try {
        exit_code = run_scan_pipeline(args, dirs, total_start);
    } catch (const rust::Error& e) {
        fmt::print(stderr, "Fatal: {}\n", std::string(e.what()));
        exit_code = 2;
    } catch (const std::exception& e) {
        fmt::print(stderr, "Fatal: {}\n", e.what());
        exit_code = 2;
    }

    classic::runtime::shutdown_runtime();
    return exit_code;
}
