#include "scanner.h"
#include "installation_root.h"
#include "progress.h"
#include "scan_run_cli.h"

#ifdef _WIN32
#include <io.h>
#else
#include <unistd.h>
#endif

#include "rust/cxx.h"

// CXX bridge headers (generated by corrosion_add_cxxbridge)
#include "classic_cxx_bridge/message.h"
#include "classic_cxx_bridge/registry.h"
#include "classic_cxx_bridge/runtime.h"
#include "classic_cxx_bridge/scanner.h"
#include "classic_cxx_bridge/settings.h"

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fmt/core.h>
#include <iostream>
#include <memory>
#include <string>
#include <utility>

namespace fs = std::filesystem;

/// Returns whether standard input is attached to an interactive terminal.
///
/// Used to decide whether asking the user a blocking question is legitimate. A redirected or
/// inherited stdin that never closes would otherwise leave a scripted run parked in `std::getline`
/// forever, with an interactive menu printed into whatever consumes the CLI's stdout.
static bool stdin_is_interactive() {
#ifdef _WIN32
    return _isatty(_fileno(stdin)) != 0;
#else
    return isatty(fileno(stdin)) != 0;
#endif
}

// ── Data root discovery ────────────────────────────────────────────

struct DataDirs {
    std::string root;
};

// ── Filename extraction helper ─────────────────────────────────────

static std::string filename_from_path(const std::string& path) {
    auto pos = path.find_last_of("/\\");
    return (pos != std::string::npos) ? path.substr(pos + 1) : path;
}

static std::string rust_string_to_std(const rust::String& value) {
    return std::string(value.data(), value.size());
}

static std::string startup_correlation_id() {
    char* env_value = nullptr;
    size_t env_len = 0;
    if (_dupenv_s(&env_value, &env_len, "CLASSIC_CORRELATION_ID") != 0 || env_value == nullptr) {
        return {};
    }

    std::string correlation_id(env_value);
    free(env_value);
    if (correlation_id.empty()) {
        return {};
    }
    return correlation_id;
}

/// Writes one durable presentation line to its requested console channel.
static void print_cli_scan_message(const CliScanRunMessage& message) {
    if (message.error) {
        fmt::print(stderr, "{}\n", message.text);
    } else {
        fmt::print("{}\n", message.text);
    }
}

/// Presents serialized final-contract events and reports adapter failures as failed deliveries.
///
/// It neither cancels nor remembers a failure: Rust applies `CLI_SCAN_RUN_OBSERVER_FAILURE_POLICY`
/// and reports the failure on the run result, which is where the CLI reads it.
class CliScanRunObserver final : public classic::scanner::ScanRunObserver {
public:
    /// Creates an observer that labels its progress display with `game`.
    explicit CliScanRunObserver(std::string game)
        : game_(std::move(game)) {}

    /// Renders one event without allowing presentation failures to cross CXX.
    ///
    /// A presentation failure is returned as a failed delivery; Rust applies the cancel-run
    /// policy `execute_cli_scan_run` passes and reports the failure in the envelope.
    classic::scanner::ScanRunObserverDelivery on_scan_run_event(
        const classic::scanner::ScanRunContractEvent& event) const noexcept override {
        try {
            if (event.kind == classic::scanner::ScanRunContractEventKind::DiscoveryCompleted) {
                progress_ = std::make_unique<ProgressDisplay>(
                    static_cast<uint32_t>(event.discovery.accepted_logs.size()), game_);
            }

            if (progress_) {
                // Clear the prior dynamic frame before printing durable event text so the next
                // render does not erase discovery, concurrency, or per-log messages.
                progress_->finish();
            }
            for (const auto& message : describe_cli_scan_run_event(event)) {
                print_cli_scan_message(message);
            }

            if (!progress_) {
                return {};
            }

            const std::string key = std::to_string(event.discovery_index);
            switch (event.kind) {
            case classic::scanner::ScanRunContractEventKind::LogStarted:
                progress_->report_started(key, filename_from_path(rust_string_to_std(event.crash_log)));
                break;
            case classic::scanner::ScanRunContractEventKind::LogFinished:
                if (event.disposition == classic::scanner::ScanRunContractLogDisposition::Failed) {
                    progress_->report_error(key);
                } else {
                    progress_->report_finished(key);
                }
                break;
            case classic::scanner::ScanRunContractEventKind::DiscoveryCompleted:
            case classic::scanner::ScanRunContractEventKind::EffectiveConcurrencySelected:
            case classic::scanner::ScanRunContractEventKind::LogQueued:
            case classic::scanner::ScanRunContractEventKind::LogPhase:
                break;
            }
            progress_->render();
            return {};
        } catch (...) {
            return {true, "scan progress presentation failed"};
        }
    }

    /// Clears any live progress rendering after synchronous execution returns.
    void finish() const {
        if (progress_) {
            progress_->finish();
        }
    }

private:
    std::string game_;
    mutable std::unique_ptr<ProgressDisplay> progress_;
};

// ── Scan pipeline (inner) ──────────────────────────────────────────
// Factored out so rust::Box<T> objects can be constructed in-place
// rather than pre-declared (rust::Box is non-nullable, no nullptr init).

/// Launches through Crash Log Scan Launch, runs the single Rust-owned operation, and presents its
/// typed outcome.
static int run_scan_pipeline(const CliArgs& args, const DataDirs& dirs,
                             std::chrono::steady_clock::time_point total_start) {
    // Rust builds the request from saved User Settings and the flags' overrides. A Standard scan
    // looks for Crash Logs under the Installation Root, never under this process's working folder.
    const auto launch = launch_cli_scan_run(args, dirs.root);
    if (!launch.has_value()) {
        return 1;
    }
    const auto launch_error = classic::scanner::scan_run_launch_error(**launch);
    if (launch_error.has_error) {
        fmt::print(stderr, "Fatal: could not launch the Crash Log Scan Run: {}\n",
                   rust_string_to_std(launch_error.message));
        return 2;
    }
    const auto view = classic::scanner::scan_run_launch_view(**launch);
    for (const auto& message : describe_cli_scan_run_launch(view)) {
        print_cli_scan_message(message);
    }

    const std::string game = cli_scan_run_game_token(view.configuration.game);
    const std::string game_version = rust_string_to_std(view.configuration.game_version);
    classic::registry::registry_set_game(game);
    std::string mode_suffix;
    if (game_version != "auto") {
        mode_suffix += " " + game_version;
    }
    if (view.fcx_enabled) {
        mode_suffix += " [FCX]";
    }
    fmt::print("CLASSIC v{} - Crash Log Scanner ({}{})\n\n", CLASSIC_CLI_VERSION, game, mode_suffix);

    const auto request = classic::scanner::scan_run_launch_request(**launch);
    CliScanRunCancellation cancellation;
    CliScanRunObserver observer(game);

    // Local Ignore recovery is an expected interactive choice, not a failure. The prompt clears any
    // live progress frame first so the question is not overwritten by the next render.
    //
    // Installed only when stdin is a terminal. `execute_cli_scan_run` treats an empty prompt as the
    // non-interactive path and returns the typed recovery-required envelope instead of asking, which
    // is the right answer for a scripted run: `read_cli_local_ignore_recovery_choice` cancels
    // cleanly on EOF, but a non-TTY stdin that stays open (a CI wrapper, a service manager, a pipe
    // whose writer is idle) has no EOF to give and the run would block indefinitely on a question
    // no one can see.
    CliLocalIgnoreRecoveryPrompt recovery_prompt;
    if (stdin_is_interactive()) {
        recovery_prompt = [&observer, &cancellation](const CliLocalIgnoreRecoveryPresentation& recovery) {
            observer.finish();
            fmt::print("\n");
            for (const auto& message : recovery.details) {
                print_cli_scan_message(message);
            }
            return read_cli_local_ignore_recovery_choice(std::cin, std::cout, cancellation, recovery.decisions);
        };
    }

    const auto outcome = execute_cli_scan_run(*request, cancellation, &observer, recovery_prompt);
    observer.finish();

    const auto total_end = std::chrono::steady_clock::now();
    const double duration = std::chrono::duration<double>(total_end - total_start).count();
    const auto presentation = present_cli_scan_run_outcome(outcome, duration);
    fmt::print("\n");
    for (const auto& message : presentation.messages) {
        print_cli_scan_message(message);
    }
    return presentation.exit_code;
}

// ── Public entry point ─────────────────────────────────────────────

int run_scan(const CliArgs& args) {
    return run_scan(args, current_cli_process_location());
}

int run_scan(const CliArgs& args, const CliProcessLocation& location) {
    auto total_start = std::chrono::steady_clock::now();

    // Locate the Installation Root before the runtime starts: a run from the wrong folder stops
    // here with "CLASSIC Data not found" instead of scanning that folder as if it were the
    // installation (the old private search fell back to the working directory).
    const auto installation_root = require_cli_installation_root(location);
    if (!installation_root) {
        return kCliInstallationRootNotFoundExitCode;
    }
    const DataDirs dirs{*installation_root};

    const std::string correlation_id = startup_correlation_id();

    // Initialize Rust runtime + logging
    try {
        classic::message::init_logging();
        classic::runtime::init_runtime();
        classic::message::log_startup_binding_contract_validated("classic-cli.startup", 3, correlation_id);
        classic::message::log_startup_acceleration_status(1, 1, "MANDATORY", correlation_id);
    } catch (const rust::Error& e) {
        classic::message::log_startup_binding_contract_failed(
            "classic-cli.startup", "classic::runtime::init_runtime", "runtime_init",
            "Run classic-cli/build_cli.ps1 to rebuild the C++ bridge and verify runtime dependencies.", e.what(),
            correlation_id);
        fmt::print(stderr, "Fatal: failed to initialize runtime: {}\n", std::string(e.what()));
        return 2;
    }

    fmt::print("Data root: {}\n", dirs.root);
    fmt::print("\n");

    // Run the scan pipeline (all rust::Box<T> objects live inside this scope)
    int exit_code;
    try {
        exit_code = run_scan_pipeline(args, dirs, total_start);
    } catch (const rust::Error& e) {
        fmt::print(stderr, "Fatal: {}\n", std::string(e.what()));
        exit_code = 2;
    } catch (const std::exception& e) {
        fmt::print(stderr, "Fatal: {}\n", e.what());
        exit_code = 2;
    }

    classic::runtime::shutdown_runtime();
    return exit_code;
}
