//! PyO3 bindings for Wrye Bash plugin checker report parsing

use classic_scangame_core::{WryeBashParser, WryeIssue, WryeSeverity};
use pyo3::prelude::*;
use std::collections::HashMap;

/// Python wrapper for WryeSeverity
#[pyclass(name = "WryeSeverity")]
#[derive(Clone)]
pub enum PyWryeSeverity {
    /// Informational notice
    Info,
    /// Warning requiring attention
    Warning,
    /// Error requiring immediate action
    Error,
}

/// Python wrapper for WryeIssue
#[pyclass(name = "WryeIssue")]
#[derive(Clone)]
pub struct PyWryeIssue {
    /// Section title from the report
    #[pyo3(get)]
    pub section_title: String,

    /// Plugin names associated with this section
    #[pyo3(get)]
    pub plugins: Vec<String>,

    /// Warning message from the YAML database, if any
    #[pyo3(get)]
    pub warning_message: Option<String>,

    /// Issue severity
    #[pyo3(get)]
    pub severity: PyWryeSeverity,
}

#[pymethods]
impl PyWryeIssue {
    fn __repr__(&self) -> String {
        format!(
            "WryeIssue(section='{}', plugins={}, severity={:?})",
            self.section_title,
            self.plugins.len(),
            match self.severity {
                PyWryeSeverity::Info => "Info",
                PyWryeSeverity::Warning => "Warning",
                PyWryeSeverity::Error => "Error",
            }
        )
    }
}

/// Python wrapper for WryeBashParser
///
/// Parses ModChecker.html reports generated by Wrye Bash's Plugin Checker.
///
/// Example:
///     >>> parser = WryeBashParser({"Missing Masters": "  Fix load order!\n"})
///     >>> issues = parser.parse(html_content)
///     >>> report = WryeBashParser.format_report(issues)
///     >>> print(report)
#[pyclass(name = "WryeBashParser")]
pub struct PyWryeBashParser {
    inner: WryeBashParser,
}

#[pymethods]
impl PyWryeBashParser {
    #[new]
    #[pyo3(signature = (wrye_warnings=None))]
    fn new(wrye_warnings: Option<HashMap<String, String>>) -> Self {
        Self {
            inner: WryeBashParser::new(wrye_warnings.unwrap_or_default()),
        }
    }

    /// Parse an HTML Wrye Bash report and extract issues
    ///
    /// Args:
    ///     html_content: Raw HTML string from ModChecker.html
    ///
    /// Returns:
    ///     List of WryeIssue objects
    fn parse(&self, html_content: &str) -> Vec<PyWryeIssue> {
        self.inner
            .parse(html_content)
            .into_iter()
            .map(|issue| PyWryeIssue {
                section_title: issue.section_title,
                plugins: issue.plugins,
                warning_message: issue.warning_message,
                severity: convert_severity(&issue.severity),
            })
            .collect()
    }

    /// Format parsed issues into a complete report string
    ///
    /// Args:
    ///     issues: List of WryeIssue objects from parse()
    ///
    /// Returns:
    ///     Formatted report string
    #[staticmethod]
    fn format_report(issues: Vec<PyWryeIssue>) -> String {
        let core_issues: Vec<WryeIssue> = issues
            .into_iter()
            .map(|py_issue| WryeIssue {
                section_title: py_issue.section_title,
                plugins: py_issue.plugins,
                warning_message: py_issue.warning_message,
                severity: match py_issue.severity {
                    PyWryeSeverity::Info => WryeSeverity::Info,
                    PyWryeSeverity::Warning => WryeSeverity::Warning,
                    PyWryeSeverity::Error => WryeSeverity::Error,
                },
            })
            .collect();

        WryeBashParser::format_report(&core_issues)
    }

    fn __repr__(&self) -> String {
        "WryeBashParser(...)".to_string()
    }
}

/// Convert core WryeSeverity to Python wrapper
fn convert_severity(severity: &WryeSeverity) -> PyWryeSeverity {
    match severity {
        WryeSeverity::Info => PyWryeSeverity::Info,
        WryeSeverity::Warning => PyWryeSeverity::Warning,
        WryeSeverity::Error => PyWryeSeverity::Error,
    }
}

/// Convenience function to parse a Wrye Bash report and return formatted text
///
/// Args:
///     html_content: Raw HTML from ModChecker.html
///     wrye_warnings: Warning messages keyed by section title substring
///
/// Returns:
///     Formatted report string
#[pyfunction]
#[pyo3(signature = (html_content, wrye_warnings=None))]
pub fn parse_wrye_report(
    html_content: &str,
    wrye_warnings: Option<HashMap<String, String>>,
) -> String {
    let parser = WryeBashParser::new(wrye_warnings.unwrap_or_default());
    let issues = parser.parse(html_content);
    WryeBashParser::format_report(&issues)
}

/// Register wrye module functions with Python module
pub fn register_wrye(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<PyWryeBashParser>()?;
    m.add_class::<PyWryeIssue>()?;
    m.add_class::<PyWryeSeverity>()?;
    m.add_function(wrap_pyfunction!(parse_wrye_report, m)?)?;
    Ok(())
}
