"""Add 23 normal config rows to parity_contract.json for Plan 03."""
import json
from pathlib import Path

REPO = Path("J:/CLASSIC-Fallout4")
contract_path = REPO / "docs/implementation/node_api_parity/baseline/parity_contract.json"
contract = json.loads(contract_path.read_text())

normal_rows = [
    # Consts (3)
    {
        "id": "config.caches.DEFAULT_CACHE_CLEANUP_INTERVAL",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "DEFAULT_CACHE_CLEANUP_INTERVAL_SECS",
        "rustKind": "const",
        "nodeExport": "DEFAULT_CACHE_CLEANUP_INTERVAL",
        "nodeKind": "const",
    },
    {
        "id": "config.caches.DEFAULT_CACHE_CLEANUP_THRESHOLD",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "DEFAULT_CACHE_CLEANUP_OP_THRESHOLD",
        "rustKind": "const",
        "nodeExport": "DEFAULT_CACHE_CLEANUP_THRESHOLD",
        "nodeKind": "const",
    },
    {
        "id": "config.caches.DEFAULT_QUERY_CACHE_CAPACITY",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "DEFAULT_QUERY_CACHE_CAPACITY",
        "rustKind": "const",
        "nodeExport": "DEFAULT_QUERY_CACHE_CAPACITY",
        "nodeKind": "const",
    },
    # Interfaces (9)
    {
        "id": "config.hash_cache.HashCacheStats",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "CacheStats",
        "rustKind": "class",
        "nodeExport": "HashCacheStats",
        "nodeKind": "interface",
    },
    {
        "id": "config.analysis.JsAnalysisConfig",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "AnalysisConfig",
        "rustKind": "class",
        "nodeExport": "JsAnalysisConfig",
        "nodeKind": "interface",
    },
    {
        "id": "config.scangame.JsConfigIssue",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "ConfigIssue",
        "rustKind": "class",
        "nodeExport": "JsConfigIssue",
        "nodeKind": "interface",
    },
    {
        "id": "config.fcx.JsFcxConfigIssue",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "ConfigIssue",
        "rustKind": "class",
        "nodeExport": "JsFcxConfigIssue",
        "nodeKind": "interface",
    },
    {
        "id": "config.scangame.JsGameScanConfig",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "GameScanConfig",
        "rustKind": "class",
        "nodeExport": "JsGameScanConfig",
        "nodeKind": "interface",
    },
    {
        "id": "config.scangame.JsIntegrityConfig",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "IntegrityConfig",
        "rustKind": "class",
        "nodeExport": "JsIntegrityConfig",
        "nodeKind": "interface",
    },
    {
        "id": "config.path.JsPathDetectionResult",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "needs_path_detection",
        "rustKind": "function",
        "nodeExport": "JsPathDetectionResult",
        "nodeKind": "interface",
    },
    {
        "id": "config.scangame.JsTomlConfigIssue",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "TomlConfigIssue",
        "rustKind": "class",
        "nodeExport": "JsTomlConfigIssue",
        "nodeKind": "interface",
    },
    {
        "id": "config.version_registry.JsXseConfig",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "XseConfig",
        "rustKind": "class",
        "nodeExport": "JsXseConfig",
        "nodeKind": "interface",
    },
    # const_enum (1)
    {
        "id": "config.scangame.JsEnbConfigResult",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "EnbConfigResult",
        "rustKind": "enum",
        "nodeExport": "JsEnbConfigResult",
        "nodeKind": "const_enum",
    },
    # Class (1)
    {
        "id": "config.duplicate_detector.JsConfigDuplicateDetector",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "ConfigDuplicateDetector",
        "rustKind": "class",
        "nodeExport": "JsConfigDuplicateDetector",
        "nodeKind": "class",
    },
    # Functions (9)
    {
        "id": "config.hash_cache.clearHashCache",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "clear_hash_cache",
        "rustKind": "function",
        "nodeExport": "clearHashCache",
        "nodeKind": "function",
    },
    {
        "id": "config.duplicate_detector.detectConfigDuplicates",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "detect_config_duplicates",
        "rustKind": "function",
        "nodeExport": "detectConfigDuplicates",
        "nodeKind": "function",
    },
    {
        "id": "config.caches.getDefaultCacheCleanupInterval",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "get_default_cache_cleanup_interval",
        "rustKind": "function",
        "nodeExport": "getDefaultCacheCleanupInterval",
        "nodeKind": "function",
    },
    {
        "id": "config.caches.getDefaultCacheCleanupThreshold",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "get_default_cache_cleanup_threshold",
        "rustKind": "function",
        "nodeExport": "getDefaultCacheCleanupThreshold",
        "nodeKind": "function",
    },
    {
        "id": "config.caches.getDefaultQueryCacheCapacity",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "get_default_query_cache_capacity",
        "rustKind": "function",
        "nodeExport": "getDefaultQueryCacheCapacity",
        "nodeKind": "function",
    },
    {
        "id": "config.fcx.getFcxConfigIssues",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "get_fcx_config_issues",
        "rustKind": "function",
        "nodeExport": "getFcxConfigIssues",
        "nodeKind": "function",
    },
    {
        "id": "config.hash_cache.getHashCacheStats",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "get_hash_cache_stats",
        "rustKind": "function",
        "nodeExport": "getHashCacheStats",
        "nodeKind": "function",
    },
    {
        "id": "config.path.needsPathDetection",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "needs_path_detection",
        "rustKind": "function",
        "nodeExport": "needsPathDetection",
        "nodeKind": "function",
    },
    {
        "id": "config.hash_cache.resetHashCacheStats",
        "tier": "tier1",
        "ownerModule": "config",
        "rustCrate": "classic-config-core",
        "rustSymbol": "reset_hash_cache_stats",
        "rustKind": "function",
        "nodeExport": "resetHashCacheStats",
        "nodeKind": "function",
    },
]

contract["tier1Mappings"].extend(normal_rows)
print(f"Added {len(normal_rows)} normal rows")
print(f"Total tier1Mappings: {len(contract['tier1Mappings'])}")

contract_path.write_text(json.dumps(contract, indent=2) + "\n")
print("Written to parity_contract.json")
