use super::*;
use crate::version::CrashgenVersionStatus;
use classic_config_core::{AutoscanReportPlacement, OutcomeKind, RuleSeverity};

fn base_facts() -> AutoscanReportFacts {
    AutoscanReportFacts {
        classic_version: "v9.0.0".to_string(),
        crashlog_filename: "crash.log".to_string(),
        main_error: "Unhandled exception \"EXCEPTION_ACCESS_VIOLATION\"".to_string(),
        crashgen_name: "Buffout 4".to_string(),
        crashgen_version: "Buffout 4 v1.28.6".to_string(),
        crashgen_status: Some(CrashgenVersionStatus::Valid),
        fake_bot_compatible_mode: false,
        fcx_mode_enabled: false,
    }
}

fn expectation(message: &str, placement: AutoscanReportPlacement) -> AutoscanReportContribution {
    AutoscanReportContribution::CrashgenExpectation(CrashgenExpectationContribution {
        kind: OutcomeKind::Notice,
        severity: RuleSeverity::Warning,
        message: message.to_string(),
        fix: None,
        placement,
    })
}

#[test]
fn test_string_pool() {
    let pool = StringPool::new();

    let s1 = pool.intern("hello");
    let s2 = pool.intern("hello");
    assert_eq!(s1, s2);

    let (size, lookups, hits, insertions) = pool.get_stats();
    assert_eq!(size, 1);
    assert_eq!(lookups, 2);
    assert_eq!(hits, 1);
    assert_eq!(insertions, 1);
}

#[test]
fn test_report_fragment() {
    let fragment1 = ReportFragment::from_lines(vec!["line1".to_string(), "line2".to_string()]);
    let fragment2 = ReportFragment::from_lines(vec!["line3".to_string()]);

    let combined = fragment1.combine(&fragment2);
    assert_eq!(combined.len(), 3);
    assert_eq!(combined.to_list(), vec!["line1", "line2", "line3"]);
}

#[test]
fn test_report_composer() {
    let mut composer = ReportComposer::new();

    for i in 0..20 {
        let fragment = ReportFragment::from_lines(vec![format!("Line {}", i)]);
        composer.add(fragment);
    }

    let result = composer.compose();
    assert_eq!(result.len(), 20);
    assert_eq!(
        result.to_list(),
        (0..20).map(|i| format!("Line {}", i)).collect::<Vec<_>>()
    );

    let text = composer.build_string();
    assert!(text.contains("Line 0"));
    assert!(text.contains("Line 19"));
}

#[test]
fn test_generate_error_section_uses_list_based_valid_message() {
    let generator = ReportGenerator::with_config("v9.0.0".to_string(), "Buffout 4".to_string());

    let section = generator.generate_error_section_with_status(
        "Unhandled exception \"EXCEPTION_ACCESS_VIOLATION\"",
        "Addictol v1.0.0",
        Some(CrashgenVersionStatus::Valid),
    );

    let text = section.to_list().join("");
    assert!(text.contains("valid version of Buffout 4"));
    assert!(!text.contains("latest version of Buffout 4"));
}

#[test]
fn test_generate_error_section_fake_bot_mode_notice_replaces_version_status() {
    let generator = ReportGenerator::with_config("v9.0.0".to_string(), "Buffout 4".to_string());

    let section = generator.generate_error_section_with_status_and_fake_mode(
        "Unhandled exception \"EXCEPTION_ACCESS_VIOLATION\"",
        "Buffout 4 v1.1.0",
        None,
        true,
    );

    let text = section.to_list().join("");
    assert!(text.contains("Bot Compatible Mode"));
    assert!(text.contains("Version and Settings checks are disabled"));
    assert!(!text.contains("Unable to verify Buffout 4 version"));
}

#[test]
fn test_generate_header_uses_plain_classic_name_when_version_is_empty() {
    let generator = ReportGenerator::new();

    let text = generator.generate_header("crash.log").to_list().join("");
    assert!(text.contains("AUTOSCAN REPORT GENERATED BY CLASSIC"));
    assert!(!text.contains("CLASSIC  "));
    assert!(!text.contains("CLASSIC **"));
}

#[test]
fn test_generate_header_normalizes_decorated_classic_version() {
    let generator =
        ReportGenerator::with_config("CLASSIC v9.0.0".to_string(), "Buffout 4".to_string());

    let text = generator.generate_header("crash.log").to_list().join("");
    assert!(text.contains("AUTOSCAN REPORT GENERATED BY CLASSIC v9.0.0"));
    assert!(!text.contains("CLASSIC CLASSIC"));
}

#[test]
fn autoscan_report_assembler_applies_canonical_order_when_contributions_are_scrambled() {
    let report_lines = AutoscanReportAssembler::new().assemble(
        &base_facts(),
        vec![
            AutoscanReportContribution::FormIdFinding {
                lines: vec!["FormID finding\n".to_string()],
            },
            expectation("Settings placement", AutoscanReportPlacement::Settings),
            AutoscanReportContribution::PluginEvidence {
                lines: vec!["Plugin evidence\n".to_string()],
            },
            AutoscanReportContribution::CrashSuspectFinding {
                lines: vec!["Suspect finding\n".to_string()],
            },
        ],
    );
    let text = report_lines.join("");

    let header = text.find("# crash.log").unwrap();
    let error = text.find("### Error Information").unwrap();
    let suspect = text
        .find("### Checking for Known Crash Messages, Errors and Suspects")
        .unwrap();
    let settings = text
        .find("### Checking for Settings-related Issues")
        .unwrap();
    let plugin = text.find("### Checking for Plugin-related Errors").unwrap();
    let formid = text.find("### Checking FormIDs").unwrap();
    let footer = text.find("### End of Report").unwrap();

    assert!(header < error);
    assert!(error < suspect);
    assert!(suspect < settings);
    assert!(settings < plugin);
    assert!(plugin < formid);
    assert!(formid < footer);
}

#[test]
fn autoscan_report_assembler_renders_error_information_placement_before_separator() {
    let report_lines = AutoscanReportAssembler::new().assemble(
        &base_facts(),
        vec![expectation(
            "Compatibility notice",
            AutoscanReportPlacement::ErrorInformation,
        )],
    );
    let text = report_lines.join("");

    let valid_status = text.find("valid version of Buffout 4").unwrap();
    let notice = text
        .find("**# ⚠️ NOTICE : Compatibility notice #**")
        .unwrap();
    let suspect_header = text
        .find("### Checking for Known Crash Messages, Errors and Suspects")
        .unwrap();

    assert!(valid_status < notice);
    assert!(notice < suspect_header);
    assert!(text.contains("**# ⚠️ NOTICE : Compatibility notice #**\n\n---\n\n### Checking"));
}

#[test]
fn autoscan_report_assembler_renders_settings_placement_under_settings_guidance() {
    let report_lines = AutoscanReportAssembler::new().assemble(
        &base_facts(),
        vec![expectation(
            "Settings placement",
            AutoscanReportPlacement::Settings,
        )],
    );
    let text = report_lines.join("");

    let settings_header = text
        .find("### Checking for Settings-related Issues")
        .unwrap();
    let settings_notice = text.find("# ⚠️ NOTICE : Settings placement #").unwrap();

    assert!(settings_header < settings_notice);
}

#[test]
fn autoscan_report_assembler_renders_disabled_setting_notices() {
    let report_lines = AutoscanReportAssembler::new().assemble(
        &base_facts(),
        vec![AutoscanReportContribution::DisabledSettingNotice {
            setting_name: "ArchiveLimit".to_string(),
            crashgen_name: "Buffout 4".to_string(),
        }],
    );
    let text = report_lines.join("");

    assert!(text.contains("### Checking for Settings-related Issues"));
    assert!(text.contains("ArchiveLimit is disabled in your Buffout 4 settings"));
}

#[test]
fn autoscan_report_assembler_renders_no_suspects_footer_when_no_findings_exist() {
    let report_lines = AutoscanReportAssembler::new().assemble(&base_facts(), vec![]);
    let text = report_lines.join("");

    assert!(text.contains("* **NO SUSPECTS DETECTED** *"));
}

#[test]
fn autoscan_report_assembler_renders_fcx_mode_notice_from_facts() {
    let mut facts = base_facts();
    facts.fcx_mode_enabled = true;

    let report_lines = AutoscanReportAssembler::new().assemble(&facts, vec![]);
    let text = report_lines.join("");

    assert!(text.contains("FCX LOCAL FILE CHECKS ARE ENABLED"));
    assert!(text.contains("Use FCX only with crash logs from your own installation"));
}

#[test]
fn autoscan_report_assembler_preserves_report_generator_header_and_footer_text() {
    let facts = base_facts();
    let report_lines = AutoscanReportAssembler::new().assemble(&facts, vec![]);
    let text = report_lines.join("");
    let generator =
        ReportGenerator::with_config(facts.classic_version.clone(), facts.crashgen_name.clone());

    assert!(text.starts_with(&generator.generate_header("crash.log").to_list().join("")));
    assert!(text.ends_with(&generator.generate_footer().to_list().join("")));
}
