//! Wrye Bash Plugin Checker Report Parser
//!
//! Parses ModChecker.html reports generated by Wrye Bash's Plugin Checker feature.
//! Extracts plugin issues, ESL-capable plugins, and other warnings from the HTML report,
//! then formats them into human-readable diagnostic messages.
//!
//! Replaces Python `ClassicLib.scanning.game.wrye_check` with native Rust implementation
//! using the `scraper` crate (equivalent to Python's BeautifulSoup).
//!
//! ## Usage
//!
//! ```rust,no_run
//! use classic_scangame_core::wrye::WryeBashParser;
//! use std::collections::HashMap;
//!
//! let html = std::fs::read_to_string("ModChecker.html").unwrap();
//! let warnings = HashMap::new();
//! let parser = WryeBashParser::new(warnings);
//! let issues = parser.parse(&html);
//! let report = WryeBashParser::format_report(&issues);
//! println!("{}", report);
//! ```

use std::collections::HashMap;

use scraper::{ElementRef, Html, Selector};
use thiserror::Error;

/// Errors that can occur during Wrye Bash report parsing
#[derive(Debug, Error)]
pub enum WryeError {
    /// HTML parsing encountered an issue
    #[error("HTML parsing error: {0}")]
    ParseError(String),
}

/// Result type for Wrye operations
pub type Result<T> = std::result::Result<T, WryeError>;

/// Severity level for Wrye Bash issues
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum WryeSeverity {
    /// Informational notice
    Info,
    /// Warning requiring attention
    Warning,
    /// Error requiring immediate action
    Error,
}

/// An issue found in the Wrye Bash plugin checker report
#[derive(Debug, Clone)]
pub struct WryeIssue {
    /// Section title from the report (e.g., "Missing Masters", "ESL Capable")
    pub section_title: String,

    /// Plugin names associated with this section
    pub plugins: Vec<String>,

    /// Warning message from the YAML database, if any
    pub warning_message: Option<String>,

    /// Issue severity
    pub severity: WryeSeverity,
}

/// Parser for Wrye Bash ModChecker.html reports
///
/// Extracts sections (h3 headers) and their associated plugin lists from
/// the HTML report. Matches sections against a warnings dictionary loaded
/// from the YAML database.
///
/// # Example
///
/// ```rust
/// use classic_scangame_core::wrye::WryeBashParser;
/// use std::collections::HashMap;
///
/// let mut warnings = HashMap::new();
/// warnings.insert("Missing Masters".to_string(), "  Some masters are missing!\n".to_string());
///
/// let parser = WryeBashParser::new(warnings);
/// let html = "<html><body><h3>Missing Masters</h3><p>• MyMod.esp</p></body></html>";
/// let issues = parser.parse(html);
/// assert_eq!(issues.len(), 1);
/// assert_eq!(issues[0].plugins.len(), 1);
/// ```
pub struct WryeBashParser {
    /// Warning messages keyed by section title substring
    wrye_warnings: HashMap<String, String>,
}

impl WryeBashParser {
    /// Create a new parser with the given warning messages
    ///
    /// # Arguments
    ///
    /// * `wrye_warnings` - Map of warning name substrings to warning message text.
    ///   When a section title contains a key from this map, the corresponding message
    ///   is attached to the issue.
    pub fn new(wrye_warnings: HashMap<String, String>) -> Self {
        Self { wrye_warnings }
    }

    /// Parse an HTML Wrye Bash report and extract issues
    ///
    /// Processes each `<h3>` section in the HTML document, extracts plugin names
    /// from subsequent `<p>` elements, and matches sections against known warnings.
    ///
    /// # Arguments
    ///
    /// * `html_content` - Raw HTML string from ModChecker.html
    ///
    /// # Returns
    ///
    /// Vector of `WryeIssue` structs, one per section found (excluding "Active Plugins:")
    pub fn parse(&self, html_content: &str) -> Vec<WryeIssue> {
        let document = Html::parse_document(html_content);
        let Ok(h3_selector) = Selector::parse("h3") else {
            return Vec::new();
        };

        let mut issues = Vec::new();

        for h3_element in document.select(&h3_selector) {
            let title = h3_element.text().collect::<String>();

            // Skip the "Active Plugins:" section entirely (matches Python behavior)
            if title == "Active Plugins:" {
                continue;
            }

            let plugins = Self::extract_plugins_from_section(&h3_element);

            // Find matching warnings from the database
            let warning_message = self
                .wrye_warnings
                .iter()
                .find(|(warning_name, _)| title.contains(warning_name.as_str()))
                .map(|(_, text)| text.clone());

            // Determine severity based on section content
            let severity = if title == "ESL Capable" {
                WryeSeverity::Info
            } else if warning_message.is_some() {
                WryeSeverity::Warning
            } else {
                WryeSeverity::Info
            };

            issues.push(WryeIssue {
                section_title: title,
                plugins,
                warning_message,
                severity,
            });
        }

        issues
    }

    /// Extract plugin names from paragraphs following an h3 section
    ///
    /// Walks sibling `<p>` elements after the given `<h3>` and collects text that
    /// contains plugin file extensions (.esp, .esl, .esm). Stops when encountering
    /// a `<p>` that belongs to a different `<h3>` section.
    fn extract_plugins_from_section(section: &ElementRef<'_>) -> Vec<String> {
        let mut plugins = Vec::new();

        // Walk next siblings looking for <p> elements
        let mut sibling = section.next_sibling();
        while let Some(node) = sibling {
            // If we encounter another h3, stop - we've left our section
            if let Some(elem) = ElementRef::wrap(node) {
                if elem.value().name() == "h3" {
                    break;
                }

                if elem.value().name() == "p" {
                    let text = elem
                        .text()
                        .collect::<String>()
                        .trim()
                        .replace("•\u{a0} ", "");

                    if text.contains(".esp") || text.contains(".esl") || text.contains(".esm") {
                        plugins.push(text);
                    }
                }
            }

            sibling = node.next_sibling();
        }

        plugins
    }

    /// Format a section header with centered title (matching Python output)
    ///
    /// If the title is shorter than 32 characters, it gets padded with `=` signs
    /// on both sides for visual distinction.
    fn format_section_header(title: &str) -> String {
        if title.len() < 32 {
            let diff = 32 - title.len();
            let left = diff / 2;
            let right = diff - left;
            format!(
                "\n   {} {} {}\n",
                "=".repeat(left),
                title,
                "=".repeat(right)
            )
        } else {
            title.to_string()
        }
    }

    /// Format parsed issues into a complete report string
    ///
    /// Produces output matching the Python `parse_wrye_report()` function format,
    /// including section headers, ESL guidance, warning messages, and plugin lists.
    ///
    /// # Arguments
    ///
    /// * `issues` - Slice of `WryeIssue` structs from `parse()`
    ///
    /// # Returns
    ///
    /// Formatted report string ready for display
    pub fn format_report(issues: &[WryeIssue]) -> String {
        let mut parts = Vec::new();

        for issue in issues {
            // Section header
            parts.push(Self::format_section_header(&issue.section_title));

            // Special ESL Capable section
            if issue.section_title == "ESL Capable" {
                parts.push(format!(
                    "❓ There are {} plugins that can be given the ESL flag. This can be done with\n",
                    issue.plugins.len()
                ));
                parts.push(
                    "  the SimpleESLify script to avoid reaching the plugin limit (254 esm/esp).\n"
                        .to_string(),
                );
                parts.push(
                    "  SimpleESLify: https://www.nexusmods.com/skyrimspecialedition/mods/27568\n  -----\n"
                        .to_string(),
                );
            }

            // Warning message from database
            if let Some(ref warning) = issue.warning_message {
                parts.push(warning.clone());
            }

            // Plugin list (skip for ESL Capable section - matches Python behavior)
            if issue.section_title != "ESL Capable" {
                for plugin in &issue.plugins {
                    parts.push(format!("    > {plugin}\n"));
                }
            }
        }

        parts.join("")
    }
}

#[cfg(test)]
#[path = "wrye_tests.rs"]
mod tests;
