//! Public typed defaults projected without reading process or filesystem state.
use classic_user_settings_core::UserSettings;
use classic_vocabulary::Vocabulary;
use serde_json::{Value, json};

/// Observe every typed default and explicit origin through core getters.
pub(super) fn observe() -> Value {
    let snapshot = UserSettings::published_defaults();
    let mut projection = serde_json::Map::new();
    projection.insert(
        "update.update_check".into(),
        json!(snapshot.update_preferences().update_check()),
    );
    projection.insert(
        "update.update_check_origin".into(),
        json!(snapshot.update_preferences().update_check_origin().as_str()),
    );
    projection.insert(
        "update.update_source".into(),
        json!(snapshot.update_preferences().update_source().as_str()),
    );
    projection.insert(
        "update.update_source_origin".into(),
        json!(
            snapshot
                .update_preferences()
                .update_source_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.fcx_mode".into(),
        json!(snapshot.crash_log_scan_settings().fcx_mode()),
    );
    projection.insert(
        "scan.fcx_mode_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .fcx_mode_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.simplify_logs".into(),
        json!(snapshot.crash_log_scan_settings().simplify_logs()),
    );
    projection.insert(
        "scan.simplify_logs_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .simplify_logs_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.show_statistics".into(),
        json!(snapshot.crash_log_scan_settings().show_statistics()),
    );
    projection.insert(
        "scan.show_statistics_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .show_statistics_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.formid_value_lookup".into(),
        json!(snapshot.crash_log_scan_settings().formid_value_lookup()),
    );
    projection.insert(
        "scan.formid_value_lookup_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .formid_value_lookup_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.formid_databases".into(),
        json!(snapshot.crash_log_scan_settings().formid_databases()),
    );
    projection.insert(
        "scan.formid_databases_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .formid_databases_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.move_unsolved_logs".into(),
        json!(snapshot.crash_log_scan_settings().move_unsolved_logs()),
    );
    projection.insert(
        "scan.move_unsolved_logs_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .move_unsolved_logs_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.unsolved_logs_destination".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .unsolved_logs_destination()
        ),
    );
    projection.insert(
        "scan.unsolved_logs_destination_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .unsolved_logs_destination_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.custom_scan_input".into(),
        json!(snapshot.crash_log_scan_settings().custom_scan_input()),
    );
    projection.insert(
        "scan.custom_scan_input_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .custom_scan_input_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.game_version_selection".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .game_version_selection()
                .as_str()
        ),
    );
    projection.insert(
        "scan.game_version_selection_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .game_version_selection_origin()
                .as_str()
        ),
    );
    projection.insert(
        "scan.max_concurrent_scans".into(),
        json!(snapshot.crash_log_scan_settings().max_concurrent_scans()),
    );
    projection.insert(
        "scan.max_concurrent_scans_origin".into(),
        json!(
            snapshot
                .crash_log_scan_settings()
                .max_concurrent_scans_origin()
                .as_str()
        ),
    );
    projection.insert(
        "setup.managed_game".into(),
        json!(snapshot.game_setup_settings().managed_game().as_str()),
    );
    projection.insert(
        "setup.managed_game_origin".into(),
        json!(
            snapshot
                .game_setup_settings()
                .managed_game_origin()
                .as_str()
        ),
    );
    projection.insert(
        "setup.game_version_selection".into(),
        json!(
            snapshot
                .game_setup_settings()
                .game_version_selection()
                .as_str()
        ),
    );
    projection.insert(
        "setup.game_version_selection_origin".into(),
        json!(
            snapshot
                .game_setup_settings()
                .game_version_selection_origin()
                .as_str()
        ),
    );
    projection.insert(
        "setup.game_root".into(),
        json!(snapshot.game_setup_settings().game_root()),
    );
    projection.insert(
        "setup.game_root_origin".into(),
        json!(snapshot.game_setup_settings().game_root_origin().as_str()),
    );
    projection.insert(
        "setup.game_executable".into(),
        json!(snapshot.game_setup_settings().game_executable()),
    );
    projection.insert(
        "setup.game_executable_origin".into(),
        json!(
            snapshot
                .game_setup_settings()
                .game_executable_origin()
                .as_str()
        ),
    );
    projection.insert(
        "setup.documents_root".into(),
        json!(snapshot.game_setup_settings().documents_root()),
    );
    projection.insert(
        "setup.documents_root_origin".into(),
        json!(
            snapshot
                .game_setup_settings()
                .documents_root_origin()
                .as_str()
        ),
    );
    projection.insert(
        "setup.ini_folder".into(),
        json!(snapshot.game_setup_settings().ini_folder()),
    );
    projection.insert(
        "setup.ini_folder_origin".into(),
        json!(snapshot.game_setup_settings().ini_folder_origin().as_str()),
    );
    projection.insert(
        "setup.mods_root".into(),
        json!(snapshot.game_setup_settings().mods_root()),
    );
    projection.insert(
        "setup.mods_root_origin".into(),
        json!(snapshot.game_setup_settings().mods_root_origin().as_str()),
    );
    projection.insert(
        "setup.custom_scan_input".into(),
        json!(snapshot.game_setup_settings().custom_scan_input()),
    );
    projection.insert(
        "setup.custom_scan_input_origin".into(),
        json!(
            snapshot
                .game_setup_settings()
                .custom_scan_input_origin()
                .as_str()
        ),
    );
    projection.insert(
        "setup.papyrus_log".into(),
        json!(snapshot.game_setup_settings().papyrus_log()),
    );
    projection.insert(
        "setup.papyrus_log_origin".into(),
        json!(snapshot.game_setup_settings().papyrus_log_origin().as_str()),
    );
    projection.insert(
        "preferences.auto_switch_after_scan".into(),
        json!(
            snapshot
                .frontend_state()
                .preferences()
                .auto_switch_after_scan()
        ),
    );
    projection.insert(
        "preferences.auto_switch_after_scan_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .preferences()
                .auto_switch_after_scan_origin()
                .as_str()
        ),
    );
    projection.insert(
        "preferences.auto_refresh_interval_ms".into(),
        json!(
            snapshot
                .frontend_state()
                .preferences()
                .auto_refresh_interval_ms()
        ),
    );
    projection.insert(
        "preferences.auto_refresh_interval_ms_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .preferences()
                .auto_refresh_interval_ms_origin()
                .as_str()
        ),
    );
    projection.insert(
        "tui.active_tab".into(),
        json!(snapshot.frontend_state().tui().active_tab()),
    );
    projection.insert(
        "tui.active_tab_origin".into(),
        json!(snapshot.frontend_state().tui().active_tab_origin().as_str()),
    );
    projection.insert(
        "tui.results_panel_width".into(),
        json!(snapshot.frontend_state().tui().results_panel_width()),
    );
    projection.insert(
        "tui.results_panel_width_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .tui()
                .results_panel_width_origin()
                .as_str()
        ),
    );
    projection.insert(
        "tui.sort_ascending".into(),
        json!(snapshot.frontend_state().tui().sort_ascending()),
    );
    projection.insert(
        "tui.sort_ascending_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .tui()
                .sort_ascending_origin()
                .as_str()
        ),
    );
    projection.insert(
        "main_tab.maximized".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .main_tab()
                .maximized()
        ),
    );
    projection.insert(
        "main_tab.maximized_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .main_tab()
                .maximized_origin()
                .as_str()
        ),
    );
    projection.insert(
        "main_tab.width".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .main_tab()
                .width()
        ),
    );
    projection.insert(
        "main_tab.width_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .main_tab()
                .width_origin()
                .as_str()
        ),
    );
    projection.insert(
        "main_tab.height".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .main_tab()
                .height()
        ),
    );
    projection.insert(
        "main_tab.height_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .main_tab()
                .height_origin()
                .as_str()
        ),
    );
    projection.insert(
        "backups_tab.maximized".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .backups_tab()
                .maximized()
        ),
    );
    projection.insert(
        "backups_tab.maximized_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .backups_tab()
                .maximized_origin()
                .as_str()
        ),
    );
    projection.insert(
        "backups_tab.width".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .backups_tab()
                .width()
        ),
    );
    projection.insert(
        "backups_tab.width_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .backups_tab()
                .width_origin()
                .as_str()
        ),
    );
    projection.insert(
        "backups_tab.height".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .backups_tab()
                .height()
        ),
    );
    projection.insert(
        "backups_tab.height_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .backups_tab()
                .height_origin()
                .as_str()
        ),
    );
    projection.insert(
        "articles_tab.maximized".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .articles_tab()
                .maximized()
        ),
    );
    projection.insert(
        "articles_tab.maximized_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .articles_tab()
                .maximized_origin()
                .as_str()
        ),
    );
    projection.insert(
        "articles_tab.width".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .articles_tab()
                .width()
        ),
    );
    projection.insert(
        "articles_tab.width_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .articles_tab()
                .width_origin()
                .as_str()
        ),
    );
    projection.insert(
        "articles_tab.height".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .articles_tab()
                .height()
        ),
    );
    projection.insert(
        "articles_tab.height_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .articles_tab()
                .height_origin()
                .as_str()
        ),
    );
    projection.insert(
        "results_tab.maximized".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .results_tab()
                .maximized()
        ),
    );
    projection.insert(
        "results_tab.maximized_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .results_tab()
                .maximized_origin()
                .as_str()
        ),
    );
    projection.insert(
        "results_tab.width".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .results_tab()
                .width()
        ),
    );
    projection.insert(
        "results_tab.width_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .results_tab()
                .width_origin()
                .as_str()
        ),
    );
    projection.insert(
        "results_tab.height".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .results_tab()
                .height()
        ),
    );
    projection.insert(
        "results_tab.height_origin".into(),
        json!(
            snapshot
                .frontend_state()
                .window_geometry()
                .results_tab()
                .height_origin()
                .as_str()
        ),
    );
    json!({"projection": projection})
}
