"""Python module initialization

Registers all scangame components with Python:
- Config duplicate detection
- Unpacked file scanning
- Log processing
- INI validation
- TOML validation (CheckCrashgen)
- XSE plugin checking
- BA2 archive handling
- Game integrity checking (Phase 5)
"""

# Direct-import facade over the one CLASSIC native extension. Every name is
# the canonical native object, so values and exceptions created through any
# facade are the same Python types everywhere. Keep the import list and the
# literal ``__all__`` in step with ``__init__.pyi``: validate_stubs.py and the
# Python parity resolver read both.

from _classic_native._native.classic_scangame import (
    AddressLibInfo,
    BA2Issues,
    BA2Scanner,
    CheckResult,
    CheckType,
    ConfigDuplicateDetector,
    ConfigIssue,
    CrashgenCheckOrchestrator,
    CrashgenChecker,
    CrashgenReport,
    DuplicateEntry,
    DuplicateGroup,
    EnbChecker,
    EnbConfigResult,
    EnbResult,
    EnbValidationResult,
    GameIntegrityChecker,
    GameScanConfig,
    GameScanOrchestrator,
    GameScanResult,
    GameSetupCheck,
    GameSetupIntake,
    GameSetupIntakeResult,
    GameSetupPathUpdate,
    GameVersion,
    IniValidator,
    IntegrityCheckResult,
    IntegrityConfig,
    IssueSeverity,
    LogErrorEntry,
    LogProcessor,
    ModIniScanResult,
    ModScanResult,
    RustConfigFileCache,
    RustModIniScanner,
    TomlConfigIssue,
    TomlIssueSeverity,
    UnpackedIssues,
    UnpackedScanner,
    ValidationResult,
    VsyncEntry,
    WryeBashParser,
    WryeIssue,
    WryeSeverity,
    XseChecker,
    __debug_registered__,
    __version__,
    build_archived_report,
    build_combined_scan_report,
    build_unpacked_report,
    check_crashgen_config,
    check_crashgen_settings,
    check_enb,
    check_xse_plugins,
    detect_config_duplicates,
    game_setup_needs_path_detection,
    get_scan_issue_messages,
    normalize_game_setup_version_selection,
    parse_wrye_report,
    process_logs,
    run_game_setup_intake,
    run_game_setup_intake_from_user_settings,
    scan_all_ba2_archives,
    scan_mod_inis,
    scan_unpacked_files,
)

__all__ = [
    "AddressLibInfo",
    "BA2Issues",
    "BA2Scanner",
    "CheckResult",
    "CheckType",
    "ConfigDuplicateDetector",
    "ConfigIssue",
    "CrashgenCheckOrchestrator",
    "CrashgenChecker",
    "CrashgenReport",
    "DuplicateEntry",
    "DuplicateGroup",
    "EnbChecker",
    "EnbConfigResult",
    "EnbResult",
    "EnbValidationResult",
    "GameIntegrityChecker",
    "GameScanConfig",
    "GameScanOrchestrator",
    "GameScanResult",
    "GameSetupCheck",
    "GameSetupIntake",
    "GameSetupIntakeResult",
    "GameSetupPathUpdate",
    "GameVersion",
    "IniValidator",
    "IntegrityCheckResult",
    "IntegrityConfig",
    "IssueSeverity",
    "LogErrorEntry",
    "LogProcessor",
    "ModIniScanResult",
    "ModScanResult",
    "RustConfigFileCache",
    "RustModIniScanner",
    "TomlConfigIssue",
    "TomlIssueSeverity",
    "UnpackedIssues",
    "UnpackedScanner",
    "ValidationResult",
    "VsyncEntry",
    "WryeBashParser",
    "WryeIssue",
    "WryeSeverity",
    "XseChecker",
    "__debug_registered__",
    "__version__",
    "build_archived_report",
    "build_combined_scan_report",
    "build_unpacked_report",
    "check_crashgen_config",
    "check_crashgen_settings",
    "check_enb",
    "check_xse_plugins",
    "detect_config_duplicates",
    "game_setup_needs_path_detection",
    "get_scan_issue_messages",
    "normalize_game_setup_version_selection",
    "parse_wrye_report",
    "process_logs",
    "run_game_setup_intake",
    "run_game_setup_intake_from_user_settings",
    "scan_all_ba2_archives",
    "scan_mod_inis",
    "scan_unpacked_files",
]
