"""Integration Configuration Module.

Contains configuration constants and performance thresholds for the
Rust integration layer.
"""

# Environment variable to disable Rust acceleration
DISABLE_RUST_ENV_VAR = "CLASSIC_DISABLE_RUST"

# Component names
COMPONENT_PARSER = "parser"
COMPONENT_FORMID_ANALYZER = "formid_analyzer"
COMPONENT_PLUGIN_ANALYZER = "plugin_analyzer"
COMPONENT_RECORD_SCANNER = "record_scanner"
COMPONENT_REPORT_GENERATION = "report_generation"
COMPONENT_DATABASE = "database"
COMPONENT_DATABASE_POOL = "database_pool"
COMPONENT_FILE_IO = "file_io"
COMPONENT_FILE_IO_CORE = "file_io_core"
COMPONENT_MOD_DETECTOR = "mod_detector"
COMPONENT_YAML = "yaml"
COMPONENT_YAML_OPERATIONS = "yaml_operations"
COMPONENT_PATH = "path"
COMPONENT_PATH_OPERATIONS = "path_operations"
COMPONENT_YAMLDATA = "yamldata"
COMPONENT_SUSPECT_SCANNER = "suspect_scanner"
COMPONENT_SETTINGS_VALIDATOR = "settings_validator"
COMPONENT_GPU_DETECTOR = "gpu_detector"
COMPONENT_FCX_HANDLER = "fcx_handler"
COMPONENT_CONSTANTS = "constants"
COMPONENT_VERSION_UTILS = "version_utils"
COMPONENT_RESOURCE_MGMT = "resource_mgmt"
COMPONENT_XSE_UTILS = "xse_utils"
COMPONENT_WEB_UTILS = "web_utils"
COMPONENT_ORCHESTRATOR = "orchestrator"
COMPONENT_ORCHESTRATOR_BATCH = "orchestrator_batch"

# All component names list
ALL_COMPONENTS = [
    COMPONENT_PARSER,
    COMPONENT_FORMID_ANALYZER,
    COMPONENT_PLUGIN_ANALYZER,
    COMPONENT_RECORD_SCANNER,
    COMPONENT_REPORT_GENERATION,
    COMPONENT_DATABASE,
    COMPONENT_DATABASE_POOL,
    COMPONENT_FILE_IO,
    COMPONENT_FILE_IO_CORE,
    COMPONENT_MOD_DETECTOR,
    COMPONENT_YAML,
    COMPONENT_YAML_OPERATIONS,
    COMPONENT_PATH,
    COMPONENT_PATH_OPERATIONS,
    COMPONENT_YAMLDATA,
    COMPONENT_SUSPECT_SCANNER,
    COMPONENT_SETTINGS_VALIDATOR,
    COMPONENT_GPU_DETECTOR,
    COMPONENT_FCX_HANDLER,
    COMPONENT_CONSTANTS,
    COMPONENT_VERSION_UTILS,
    COMPONENT_RESOURCE_MGMT,
    COMPONENT_XSE_UTILS,
    COMPONENT_WEB_UTILS,
    COMPONENT_ORCHESTRATOR,
    COMPONENT_ORCHESTRATOR_BATCH,
]

# Performance multipliers for each component
PERFORMANCE_MULTIPLIERS = {
    COMPONENT_PARSER: "150x",
    COMPONENT_FORMID_ANALYZER: "50x",
    COMPONENT_PLUGIN_ANALYZER: "30x",
    COMPONENT_RECORD_SCANNER: "40x",
    COMPONENT_REPORT_GENERATION: "75x",
    COMPONENT_DATABASE_POOL: "25x",
    COMPONENT_FILE_IO_CORE: "10-20x file ops, 30-40x DDS",
    COMPONENT_MOD_DETECTOR: "35x",
    COMPONENT_YAML: "15-30x",
    COMPONENT_PATH: "10-20x",
    COMPONENT_SUSPECT_SCANNER: "100x",
    COMPONENT_SETTINGS_VALIDATOR: "50x",
    COMPONENT_GPU_DETECTOR: "20x",
    COMPONENT_FCX_HANDLER: "30x",
    COMPONENT_ORCHESTRATOR: "5-10x",
    COMPONENT_ORCHESTRATOR_BATCH: "10-20x",
}

# Component categories for status display
COMPONENT_CATEGORIES = {
    "ScanLog Components": [
        COMPONENT_PARSER,
        COMPONENT_FORMID_ANALYZER,
        COMPONENT_PLUGIN_ANALYZER,
        COMPONENT_RECORD_SCANNER,
        COMPONENT_REPORT_GENERATION,
        COMPONENT_MOD_DETECTOR,
        COMPONENT_SUSPECT_SCANNER,
        COMPONENT_SETTINGS_VALIDATOR,
        COMPONENT_GPU_DETECTOR,
        COMPONENT_FCX_HANDLER,
    ],
    "File I/O Components": [
        COMPONENT_FILE_IO,
        COMPONENT_FILE_IO_CORE,
    ],
    "Path Components": [
        COMPONENT_PATH,
        COMPONENT_PATH_OPERATIONS,
    ],
    "YAML Components": [
        COMPONENT_YAML,
        COMPONENT_YAML_OPERATIONS,
        COMPONENT_YAMLDATA,
    ],
    "Database Components": [
        COMPONENT_DATABASE,
        COMPONENT_DATABASE_POOL,
    ],
    "Utility Components": [
        COMPONENT_CONSTANTS,
        COMPONENT_VERSION_UTILS,
        COMPONENT_RESOURCE_MGMT,
        COMPONENT_XSE_UTILS,
        COMPONENT_WEB_UTILS,
    ],
    "Orchestration": [
        COMPONENT_ORCHESTRATOR,
        COMPONENT_ORCHESTRATOR_BATCH,
    ],
}

# Performance thresholds
PERFORMANCE_THRESHOLD_EXCELLENT = 0.9  # 90% components accelerated
PERFORMANCE_THRESHOLD_GOOD = 0.7  # 70% components accelerated
PERFORMANCE_THRESHOLD_PARTIAL = 0.3  # 30% components accelerated
