"""
Pure Python implementation of report generation.

This module provides the fallback Python implementation for generating crash
analysis reports when Rust acceleration is not available. It handles the
creation of various report sections and fragments.
"""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ClassicLib.ScanLog.ReportFragment import ReportFragment
    from ClassicLib.ScanLog.ScanLogInfo import ClassicScanLogsInfo


class PythonReportGenerator:
    """
    Pure Python implementation for generating crash analysis reports.

    This class provides the fallback implementation for generating standardized
    report fragments, including headers, error sections, suspect sections, and
    footers. It uses configuration data and contextual information to produce
    formatted outputs for identifying crash issues.

    Attributes:
        yamldata: Configuration data for generating the report.
    """

    def __init__(self, yamldata: "ClassicScanLogsInfo") -> None:
        """
        Initializes the report generator with configuration data.

        Args:
            yamldata: Instance of ClassicScanLogsInfo containing YAML data.
        """
        self.yamldata = yamldata

    def generate_header(self, crashlog_filename: str) -> "ReportFragment":
        """
        Generates a header section for an autoscan report.

        This method creates a formatted header for the generated report fragment,
        including the crash log filename and details about the autoscan version.

        Args:
            crashlog_filename: Name of the crash log file to include in the header.

        Returns:
            ReportFragment: A report fragment containing the formatted header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            f"# {crashlog_filename}\n",
            f"**AUTOSCAN REPORT GENERATED BY {version}**\n\n",
            "> **FOR BEST VIEWING EXPERIENCE OPEN THIS FILE IN NOTEPAD++ OR SIMILAR**\n\n",
            "> **PLEASE READ EVERYTHING CAREFULLY AND BEWARE OF FALSE POSITIVES**\n\n",
            "---\n\n",
        ])

    def generate_error_section(
        self,
        main_error: str,
        crashgen_version: str,
        version_current: Any,
        version_latest: Any,
        version_latest_vr: Any,
    ) -> "ReportFragment":
        """
        Generates an error section of a report with version status.

        This section includes the main error information and indicates whether
        the Crashgen version is current or outdated.

        Args:
            main_error: Primary error description.
            crashgen_version: Detected version of Crashgen.
            version_current: Currently installed Crashgen version.
            version_latest: Latest available Crashgen version.
            version_latest_vr: Latest available Crashgen version for VR.

        Returns:
            ReportFragment: Structured report fragment with error and version info.
        """
        from ClassicLib import GlobalRegistry
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        crashgen_name = self.yamldata.crashgen_name if self.yamldata else "Crashgen"
        lines = [
            "### Error Information\n\n",
            f"**Main Error:** {main_error}\n\n",
            f"**Detected {crashgen_name} Version:** {crashgen_version}\n\n",
        ]

        # Add version status
        game_is_vr = GlobalRegistry.get_vr() == "VR"
        if (version_current < version_latest_vr and version_current != version_latest) or (
            not game_is_vr and version_current < version_latest
        ):
            lines.append(f"***❌ WARNING: YOUR {crashgen_name} IS OUTDATED! PLEASE UPDATE TO THE LATEST VERSION!***\n\n")
        else:
            lines.append(f"✅ *You have the latest version of {crashgen_name}!*\n\n")

        lines.append("---\n\n")

        return ReportFragment.from_lines(lines)

    @staticmethod
    def generate_suspect_section_header() -> "ReportFragment":
        """
        Generates a header for the suspect section in the report.

        Returns:
            ReportFragment: Fragment with suspect section header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Known Crash Messages, Errors and Suspects\n\n",
        ])

    @staticmethod
    def generate_suspect_found_footer(found_suspect: bool) -> "ReportFragment":
        """
        Generate a footer section indicating whether suspects were found.

        Args:
            found_suspect: Flag indicating if suspects were detected.

        Returns:
            ReportFragment: Footer fragment with detection results.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        if found_suspect:
            return ReportFragment.from_lines([
                "* **ONE OR MORE SUSPECTS DETECTED! CHECK LOG ABOVE FOR MORE INFORMATION!** *\n\n",
                "---\n\n",
            ])
        return ReportFragment.from_lines([
            "* **NO SUSPECTS DETECTED** *\n\n",
            "---\n\n",
        ])

    @staticmethod
    def generate_settings_section_header() -> "ReportFragment":
        """
        Generates a section header for settings-related issues.

        Returns:
            ReportFragment: Fragment with settings section header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Settings-related Issues\n\n",
        ])

    @staticmethod
    def generate_mod_check_header(check_type: str) -> "ReportFragment":
        """
        Generates a report fragment header for mod checks.

        Args:
            check_type: The type of mod check to include in the header.

        Returns:
            ReportFragment: Fragment with mod check header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        return ReportFragment.from_lines([
            f"### Checking For Mods That {check_type}\n\n",
        ])

    @staticmethod
    def generate_plugin_suspect_header() -> "ReportFragment":
        """
        Generates a header for plugin-related errors section.

        Returns:
            ReportFragment: Fragment with plugin suspect header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Plugin-related Errors\n\n",
        ])

    @staticmethod
    def generate_formid_section_header() -> "ReportFragment":
        """
        Generates a section header for FormID checks.

        Returns:
            ReportFragment: Fragment with FormID section header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        return ReportFragment.from_lines([
            "### Checking FormIDs\n\n",
        ])

    @staticmethod
    def generate_record_section_header() -> "ReportFragment":
        """
        Generates a section header for named records checks.

        Returns:
            ReportFragment: Fragment with named records header.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Named Records\n\n",
        ])

    def generate_footer(self) -> "ReportFragment":
        """
        Generates a footer section for the report.

        The footer includes a line stating the end of the report and
        indicates the generator version.

        Returns:
            ReportFragment: The report fragment representing the footer.
        """
        from ClassicLib.ScanLog.ReportFragment import ReportFragment

        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            "---\n\n",
            "### End of Report\n\n",
            f"Generated by {version}\n",
        ])

# Alias for compatibility
ReportGenerator = PythonReportGenerator
