"""Pure Python implementation of report generation.

This module provides the fallback Python implementation for generating crash
analysis reports when Rust acceleration is not available. It handles the
creation of various report sections and fragments.
"""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ClassicLib.ScanLog.fragments import ReportFragment
    from ClassicLib.ScanLog.scanloginfo import ClassicScanLogsInfo


class PythonReportGenerator:
    """Pure Python implementation for generating crash analysis reports.

    This class provides the fallback implementation for generating standardized
    report fragments, including headers, error sections, suspect sections, and
    footers. It uses configuration data and contextual information to produce
    formatted outputs for identifying crash issues.

    Attributes:
        yamldata: Configuration data for generating the report.

    """

    def __init__(self, yamldata: "ClassicScanLogsInfo") -> None:
        """Initialize an instance of the class with provided scan log information.

        Args:
            yamldata (ClassicScanLogsInfo): Scan log information provided in the
                initialization of the instance.

        """
        self.yamldata = yamldata

    def generate_header(self, crashlog_filename: str) -> "ReportFragment":
        """Generate a header for the crash log report.

        This method constructs and returns a `ReportFragment` object containing the
        header information for the crash log analysis report. The header includes
        details about the crash log filename, classic version, and recommendations
        for viewing and interpreting the report.

        Args:
            crashlog_filename: The name of the crash log file.

        Returns:
            ReportFragment: An object representing the header section of the report.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            f"# {crashlog_filename}\n",
            f"**AUTOSCAN REPORT GENERATED BY {version}**\n\n",
            "> **FOR BEST VIEWING EXPERIENCE OPEN THIS FILE IN NOTEPAD++ OR SIMILAR**\n\n",
            "> **PLEASE READ EVERYTHING CAREFULLY AND BEWARE OF FALSE POSITIVES**\n\n",
            "---\n\n",
        ])

    def generate_error_section(
        self,
        main_error: str,
        crashgen_version: str,
        version_current: Any,
        version_latest: Any,
        version_latest_vr: Any,
    ) -> "ReportFragment":
        """Generate an error section for a report.

        This method creates a formatted error section with information about the main
        error, the Crashgen tool version detected, and version compatibility. It checks
        whether the current version is outdated, providing appropriate warning messages
        when necessary. The resulting section is returned as a ReportFragment.

        Args:
            main_error (str): The main error message to be included in the section.
            crashgen_version (str): The version of the Crashgen tool that has been detected.
            version_current (Any): The current version of the application or tool.
            version_latest (Any): The latest version available for the general application.
            version_latest_vr (Any): The latest version available specifically for VR.

        Returns:
            ReportFragment: A ReportFragment object containing the constructed error section.

        """
        from ClassicLib import GlobalRegistry
        from ClassicLib.ScanLog.fragments import ReportFragment

        crashgen_name = self.yamldata.crashgen_name if self.yamldata else "Crashgen"
        lines = [
            "### Error Information\n\n",
            f"**Main Error:** {main_error}\n\n",
            f"**Detected {crashgen_name} Version:** {crashgen_version}\n\n",
        ]

        # Add version status
        game_is_vr = GlobalRegistry.get_vr() == "VR"
        if (version_current < version_latest_vr and version_current != version_latest) or (
            not game_is_vr and version_current < version_latest
        ):
            lines.append(f"***❌ WARNING: YOUR {crashgen_name} IS OUTDATED! PLEASE UPDATE TO THE LATEST VERSION!***\n\n")
        else:
            lines.append(f"✅ *You have the latest version of {crashgen_name}!*\n\n")

        lines.append("---\n\n")

        return ReportFragment.from_lines(lines)

    @staticmethod
    def generate_suspect_section_header() -> "ReportFragment":
        """Generate a section header for reporting known crash messages, errors, and suspects.

        Returns:
            ReportFragment: A fragment containing the section header for the report.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Known Crash Messages, Errors and Suspects\n\n",
        ])

    @staticmethod
    def generate_suspect_found_footer(found_suspect: bool) -> "ReportFragment":
        """Generate a footer message indicating whether suspects were detected.

        This method generates a footer message suitable for inclusion in a report.
        The message provides information about the detection of one or more suspects
        or indicates the absence of any suspects. The content of the footer message
        depends on the input parameter.

        Args:
            found_suspect (bool): A flag indicating if one or more suspects were detected.
                Pass True if suspects were found and False otherwise.

        Returns:
            ReportFragment: An instance of ReportFragment containing the generated footer
                message.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        if found_suspect:
            return ReportFragment.from_lines([
                "* **ONE OR MORE SUSPECTS DETECTED! CHECK LOG ABOVE FOR MORE INFORMATION!** *\n\n",
                "---\n\n",
            ])
        return ReportFragment.from_lines([
            "* **NO SUSPECTS DETECTED** *\n\n",
            "---\n\n",
        ])

    @staticmethod
    def generate_settings_section_header() -> "ReportFragment":
        """Generate a report fragment containing the header for the settings-related issues
        section in a report.

        Returns:
            ReportFragment: A report fragment initialized with the section header lines.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Settings-related Issues\n\n",
        ])

    @staticmethod
    def generate_mod_check_header(check_type: str) -> "ReportFragment":
        """Generate a header for the mod-checking report fragment.

        This method constructs a report header containing a message about
        checking for mods that match the specified condition.

        Args:
            check_type (str): The type of mod-check condition to generate the
                report header for.

        Returns:
            ReportFragment: An instance of ReportFragment containing the
                generated header lines.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        return ReportFragment.from_lines([
            f"### Checking For Mods That {check_type}\n\n",
        ])

    @staticmethod
    def generate_plugin_suspect_header() -> "ReportFragment":
        """Generate a header fragment for reporting plugin-related errors.

        This method creates and returns a `ReportFragment` containing predefined
        content used as a header to indicate the start of a section checking
        for plugin-related errors.

        Returns:
            ReportFragment: A report fragment with the specified plugin-related
                error section header.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Plugin-related Errors\n\n",
        ])

    @staticmethod
    def generate_formid_section_header() -> "ReportFragment":
        """Generate a section header for the FormID check in the ReportFragment.

        Returns:
            ReportFragment: A new instance of ReportFragment containing the lines for
            the FormID section header.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        return ReportFragment.from_lines([
            "### Checking FormIDs\n\n",
        ])

    @staticmethod
    def generate_record_section_header() -> "ReportFragment":
        """Generate the section header for the named records portion of the report.

        This static method creates and returns a `ReportFragment` object that contains
        a predefined header to be included in a report about named records.

        Returns:
            ReportFragment: A `ReportFragment` object initialized with the appropriate
            header lines.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        return ReportFragment.from_lines([
            "### Checking for Named Records\n\n",
        ])

    def generate_footer(self) -> "ReportFragment":
        """Generate and returns a footer section for a report.

        The footer includes an end of report marker, metadata about the version
        of the tool used to generate the report, and credits for the author and
        contributors. If no specific version details are provided, a default
        "CLASSIC" value is used.

        Returns:
            ReportFragment: A formatted section representing the footer of the report.

        """
        from ClassicLib.ScanLog.fragments import ReportFragment

        version = self.yamldata.classic_version if self.yamldata else "CLASSIC"
        return ReportFragment.from_lines([
            "---\n\n",
            "### End of Report\n\n",
            f"Generated by {version}\n\n",
            "---\n\n",
            "Author/Made By: Poet (guidance.of.grace) | https://discord.gg/DfFYJtt8p4\n\n",
            "CONTRIBUTORS | evildarkarchon | kittivelae | AtomicFallout757 | wxMichael\n\n",
            "FO4 CLASSIC | https://www.nexusmods.com/fallout4/mods/56255\n",
        ])


# Alias for compatibility
ReportGenerator = PythonReportGenerator
