<#
.SYNOPSIS
    Parses coverage JSON and displays a per-crate coverage summary table.

.DESCRIPTION
    Reads the JSON coverage report generated by coverage_report.ps1 and
    groups source files by crate. Outputs a sorted table showing each
    crate's line coverage percentage and whether it meets the 60% target.

    Must run coverage_report.ps1 first to generate the JSON data.

.PARAMETER JsonPath
    Optional. Path to the coverage JSON file.
    Default: target/llvm-cov/coverage.json

.PARAMETER Threshold
    Optional. Coverage percentage threshold for PASS/GAP status.
    Default: 60

.EXAMPLE
    ./coverage_summary.ps1
    ./coverage_summary.ps1 -Threshold 70
#>

param(
    [string]$JsonPath = "target/llvm-cov/coverage.json",
    [int]$Threshold = 60
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $JsonPath)) {
    Write-Host "ERROR: Coverage JSON not found at: $JsonPath" -ForegroundColor Red
    Write-Host "Run coverage_report.ps1 first to generate coverage data." -ForegroundColor Yellow
    exit 1
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Per-Crate Coverage Summary" -ForegroundColor Cyan
Write-Host "  Threshold: ${Threshold}%" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Parse JSON
$json = Get-Content $JsonPath -Raw | ConvertFrom-Json
$files = $json.data[0].files

# Crate classification patterns
# Map directory path fragments to crate names and categories
$crateMap = @{}

foreach ($file in $files) {
    $filename = $file.filename

    # Determine crate name from file path
    $crateName = $null
    $category = $null

    # Foundation crates
    if ($filename -match "foundation[/\\]classic-shared-core[/\\]") {
        $crateName = "classic-shared-core"
        $category = "Foundation"
    }
    elseif ($filename -match "foundation[/\\]classic-shared-py[/\\]") {
        $crateName = "classic-shared-py"
        $category = "Python Bindings"
    }
    # Business logic crates
    elseif ($filename -match "business-logic[/\\](classic-[\w-]+-core)[/\\]") {
        $crateName = $Matches[1]
        $category = "Business Logic"
    }
    # Python binding crates
    elseif ($filename -match "python-bindings[/\\](classic-[\w-]+-py)[/\\]") {
        $crateName = $Matches[1]
        $category = "Python Bindings"
    }
    # UI applications
    elseif ($filename -match "ui-applications[/\\](classic-[\w-]+)[/\\]") {
        $crateName = $Matches[1]
        $category = "UI Applications"
    }
    else {
        # Skip files that don't match known crate patterns
        continue
    }

    if (-not $crateMap.ContainsKey($crateName)) {
        $crateMap[$crateName] = @{
            Name = $crateName
            Category = $category
            Covered = 0
            Total = 0
        }
    }

    $crateMap[$crateName].Covered += $file.summary.lines.covered
    $crateMap[$crateName].Total += $file.summary.lines.count
}

# Sort by category then by name
$sortedCrates = $crateMap.Values | Sort-Object -Property @{Expression={$_.Category}}, @{Expression={$_.Name}}

# Group by category
$categories = @("Foundation", "Business Logic", "UI Applications", "Python Bindings")

$totalPass = 0
$totalGap = 0
$totalCovered = 0
$totalLines = 0

# Track non-PyO3 stats separately
$corePass = 0
$coreGap = 0

foreach ($cat in $categories) {
    $crates = $sortedCrates | Where-Object { $_.Category -eq $cat }
    if ($crates.Count -eq 0) { continue }

    $isPyO3 = ($cat -eq "Python Bindings")
    $catLabel = if ($isPyO3) { "$cat (informational -- excluded from ${Threshold}% target)" } else { $cat }

    Write-Host ""
    Write-Host "--- $catLabel ---" -ForegroundColor Yellow
    Write-Host ("{0,-40} {1,10} {2,10} {3,10} {4,8}" -f "Crate", "Covered", "Total", "Coverage", "Status")
    Write-Host ("{0,-40} {1,10} {2,10} {3,10} {4,8}" -f "----", "-------", "-----", "--------", "------")

    foreach ($crate in $crates) {
        $pct = if ($crate.Total -gt 0) {
            [math]::Round(($crate.Covered / $crate.Total) * 100, 1)
        } else {
            0.0
        }

        $status = if ($pct -ge $Threshold) { "PASS" } else { "GAP" }
        $statusColor = if ($status -eq "PASS") { "Green" } else { "Red" }

        $pctStr = "$pct%"
        $line = "{0,-40} {1,10} {2,10} {3,10} {4,8}" -f $crate.Name, $crate.Covered, $crate.Total, $pctStr, $status
        Write-Host $line -ForegroundColor $statusColor

        $totalCovered += $crate.Covered
        $totalLines += $crate.Total

        if ($status -eq "PASS") { $totalPass++ } else { $totalGap++ }

        if (-not $isPyO3) {
            if ($status -eq "PASS") { $corePass++ } else { $coreGap++ }
        }
    }
}

# Workspace totals
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Workspace Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan

$totalPct = if ($totalLines -gt 0) {
    [math]::Round(($totalCovered / $totalLines) * 100, 1)
} else {
    0.0
}

Write-Host ""
Write-Host "Total crates measured:  $($totalPass + $totalGap)" -ForegroundColor White
Write-Host "  At/above ${Threshold}%:       $totalPass" -ForegroundColor Green
Write-Host "  Below ${Threshold}%:           $totalGap" -ForegroundColor Red
Write-Host ""
Write-Host "Core crates (non-PyO3):" -ForegroundColor White
Write-Host "  At/above ${Threshold}%:       $corePass" -ForegroundColor Green
Write-Host "  Below ${Threshold}%:           $coreGap" -ForegroundColor Red
Write-Host ""
Write-Host "Workspace aggregate:    $totalCovered / $totalLines ($totalPct%)" -ForegroundColor Cyan

# Gap prioritization: crates below threshold, sorted by impact (lines * gap)
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Gap Prioritization (largest impact first)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

$gaps = $sortedCrates | Where-Object {
    $pct = if ($_.Total -gt 0) { ($_.Covered / $_.Total) * 100 } else { 0 }
    ($pct -lt $Threshold) -and ($_.Category -ne "Python Bindings")
} | ForEach-Object {
    $pct = if ($_.Total -gt 0) { [math]::Round(($_.Covered / $_.Total) * 100, 1) } else { 0.0 }
    $gapLines = [math]::Ceiling($_.Total * ($Threshold - $pct) / 100)
    [PSCustomObject]@{
        Name = $_.Name
        Coverage = $pct
        Total = $_.Total
        GapLines = $gapLines
        Impact = $_.Total * ($Threshold - $pct)
    }
} | Sort-Object -Property Impact -Descending

if ($gaps.Count -eq 0) {
    Write-Host "All core crates meet the ${Threshold}% target!" -ForegroundColor Green
} else {
    Write-Host ("{0,-40} {1,10} {2,10} {3,12}" -f "Crate", "Coverage", "Total", "Lines to 60%")
    Write-Host ("{0,-40} {1,10} {2,10} {3,12}" -f "----", "--------", "-----", "------------")
    foreach ($gap in $gaps) {
        $covStr = "$($gap.Coverage)%"
        $line = "{0,-40} {1,10} {2,10} {3,12}" -f $gap.Name, $covStr, $gap.Total, $gap.GapLines
        Write-Host $line -ForegroundColor Red
    }
}

Write-Host ""
