"""Functional report generator using fragments.

.. deprecated::
    This module is deprecated and will be removed in a future version.
    Use ClassicLib.integration.factory.get_report_generator() which returns
    the Rust-accelerated RustAcceleratedReportGenerator.

    The Rust implementation provides 75x performance improvement and is now
    the only supported implementation as of Phase 8 of the Rust migration.

This module provides functional versions of report generation methods
that return immutable fragments instead of mutating shared state.
"""

from __future__ import annotations

import warnings
from typing import Any

from ClassicLib.scanning.logs.reporting.report_fragment import ReportFragment


class ReportGeneratorFunctional:
    """Pure Python report generator (DEPRECATED).

    .. deprecated::
        This class is deprecated. Use get_report_generator() from
        ClassicLib.integration.factory instead.

    This implementation remains for reference but is no longer used in
    production code paths. The Rust ReportGenerator is now the sole
    implementation.

    This class provides static methods to generate specific fragments of a report
    such as the header, error information section, and suspect section. These
    fragments can be used to build comprehensive reports for analyzing crash
    logs.
    """

    def __init__(self, yamldata: Any = None) -> None:
        """Initialize the deprecated ReportGeneratorFunctional.

        Args:
            yamldata: Optional YAML data configuration. Unused in static methods.

        """
        warnings.warn(
            "ReportGeneratorFunctional is deprecated and will be removed. Use get_report_generator() from ClassicLib.integration.factory.",
            DeprecationWarning,
            stacklevel=2,
        )
        self.yamldata = yamldata

    @staticmethod
    def generate_header(crashlog_filename: str, version: str) -> ReportFragment:
        """Generate a formatted header for an autoscan report.

        The generated header includes information about the crashlog file name and the
        version of the tool that created the report. It provides suggestions for the
        best viewing experience and includes a cautionary message about false
        positives.

        Args:
            crashlog_filename (str): The name of the crashlog file related to the report.
            version (str): The version of the tool generating the report.

        Returns:
            ReportFragment: A fragment containing the formatted header for the report.

        """
        return ReportFragment.from_lines([
            f"# {crashlog_filename}\n",
            f"**AUTOSCAN REPORT GENERATED BY {version}**\n\n",
            "> **FOR BEST VIEWING EXPERIENCE OPEN THIS FILE IN NOTEPAD++ OR SIMILAR**\n\n",
            "> **PLEASE READ EVERYTHING CAREFULLY AND BEWARE OF FALSE POSITIVES**\n\n",
            "---\n\n",
        ])

    @staticmethod
    def generate_error_section(
        main_error: str,
        crashgen_version: str,
        crashgen_name: str,
        is_latest: bool,
        warn_outdated: str,
    ) -> ReportFragment:
        """Generate an error section for the crash report.

        This method composes a section containing detailed error information and other
        contextual metadata related to a crash. The generated section includes details
        like the main error, the version information of the crash generator, and whether
        the latest version is being used. Additionally, if the crash generator version
        is outdated, a warning message is included.

        Args:
            main_error (str): The main error message describing the issue.
            crashgen_version (str): The version string of the crash generator detected.
            crashgen_name (str): The name of the crash generator.
            is_latest (bool): Indicates whether the current version of the crash generator
                is the latest available.
            warn_outdated (str): A warning message for cases when the crash generator
                version is outdated.

        Returns:
            ReportFragment: A formatted report fragment containing the error section.

        """
        lines = [
            "### Error Information\n\n",
            f"**Main Error:** {main_error}\n\n",
            f"**Detected {crashgen_name} Version:** {crashgen_version}\n\n",
        ]

        if is_latest:
            lines.append(f"✅ *You have the latest version of {crashgen_name}!*\n\n")
        else:
            lines.append(f"⚠️ {warn_outdated}\n\n")

        return ReportFragment.from_lines(lines)

    @staticmethod
    def generate_suspect_section(found_suspects: list[str]) -> ReportFragment:
        """Generate a suspect section for a report based on identified crash suspects.

        This method compiles lines of text based on whether any suspects of crashes have
        been found. If no suspects are identified, the method generates a section stating
        that no suspects were found. If suspects are found, it lists them and appends
        detailed help links for further troubleshooting.

        Args:
            found_suspects (list[str]): A list of strings where each string represents a
                potential crash suspect detected in the log.

        Returns:
            ReportFragment: A report fragment containing the completed suspect analysis
            section, formatted as lines of text.

        """
        if not found_suspects:
            return ReportFragment.from_lines([
                "### Checking If Log Matches Any Known Crash Suspects\n\n",
                "# FOUND NO CRASH ERRORS / SUSPECTS THAT MATCH THE CURRENT DATABASE #\n",
                "Check below for mods that can cause frequent crashes and other problems.\n\n",
            ])

        lines = ["### Checking If Log Matches Any Known Crash Suspects\n\n"]
        lines.extend(found_suspects)
        lines.extend([
            "* FOR DETAILED DESCRIPTIONS AND POSSIBLE SOLUTIONS TO ANY ABOVE DETECTED CRASH SUSPECTS *\n",
            "* SEE: https://docs.google.com/document/d/17FzeIMJ256xE85XdjoPvv_Zi3C5uHeSTQh6wOZugs4c *\n\n",
        ])

        return ReportFragment.from_lines(lines)
