"""Complete typed defaults observed through public projection getters."""

from collections.abc import Mapping
from dataclasses import replace
from typing import Any

from ..coverage import CoveragePredicate

FIELDS = (
    "update.update_check",
    "update.update_check_origin",
    "update.update_source",
    "update.update_source_origin",
    "scan.fcx_mode",
    "scan.fcx_mode_origin",
    "scan.simplify_logs",
    "scan.simplify_logs_origin",
    "scan.show_statistics",
    "scan.show_statistics_origin",
    "scan.formid_value_lookup",
    "scan.formid_value_lookup_origin",
    "scan.formid_databases",
    "scan.formid_databases_origin",
    "scan.move_unsolved_logs",
    "scan.move_unsolved_logs_origin",
    "scan.unsolved_logs_destination",
    "scan.unsolved_logs_destination_origin",
    "scan.custom_scan_input",
    "scan.custom_scan_input_origin",
    "scan.game_version_selection",
    "scan.game_version_selection_origin",
    "scan.max_concurrent_scans",
    "scan.max_concurrent_scans_origin",
    "setup.managed_game",
    "setup.managed_game_origin",
    "setup.game_version_selection",
    "setup.game_version_selection_origin",
    "setup.game_root",
    "setup.game_root_origin",
    "setup.game_executable",
    "setup.game_executable_origin",
    "setup.documents_root",
    "setup.documents_root_origin",
    "setup.ini_folder",
    "setup.ini_folder_origin",
    "setup.mods_root",
    "setup.mods_root_origin",
    "setup.custom_scan_input",
    "setup.custom_scan_input_origin",
    "setup.papyrus_log",
    "setup.papyrus_log_origin",
    "preferences.auto_switch_after_scan",
    "preferences.auto_switch_after_scan_origin",
    "preferences.auto_refresh_interval_ms",
    "preferences.auto_refresh_interval_ms_origin",
    "tui.active_tab",
    "tui.active_tab_origin",
    "tui.results_panel_width",
    "tui.results_panel_width_origin",
    "tui.sort_ascending",
    "tui.sort_ascending_origin",
    "main_tab.maximized",
    "main_tab.maximized_origin",
    "main_tab.width",
    "main_tab.width_origin",
    "main_tab.height",
    "main_tab.height_origin",
    "backups_tab.maximized",
    "backups_tab.maximized_origin",
    "backups_tab.width",
    "backups_tab.width_origin",
    "backups_tab.height",
    "backups_tab.height_origin",
    "articles_tab.maximized",
    "articles_tab.maximized_origin",
    "articles_tab.width",
    "articles_tab.width_origin",
    "articles_tab.height",
    "articles_tab.height_origin",
    "results_tab.maximized",
    "results_tab.maximized_origin",
    "results_tab.width",
    "results_tab.width_origin",
    "results_tab.height",
    "results_tab.height_origin",
)


def matches_defaults(observation: Mapping[str, Any]) -> bool:
    """Require every default projection field, including explicit provenance."""
    projection = observation.get("projection")
    return (
        set(observation) == {"projection"}
        and isinstance(projection, Mapping)
        and set(projection) == set(FIELDS)
        and all(
            projection[key] == "default" for key in FIELDS if key.endswith("_origin")
        )
    )


DEFAULTS_PROJECTION_PREDICATE = CoveragePredicate(
    "user-settings.defaults.projection",
    "user-settings.open",
    "user-settings.defaults",
    "projection",
    (
        "UpdatePreferences",
        "CrashLogScanSettings",
        "GameSetupSettings",
        "FrontendPreferences",
        "FrontendState",
        "GuiWindowGeometry",
        "WindowGeometry",
        "TuiRememberedState",
    ),
    matches_defaults,
    runtime_operations=(
        None,
        "user_settings_gui_published_defaults",
        "publishedUserSettingsDefaults",
        "user_settings_published_defaults",
        "active_tab",
        "active_tab_origin",
        "auto_refresh_interval_ms",
        "auto_refresh_interval_ms_origin",
        "auto_switch_after_scan",
        "auto_switch_after_scan_origin",
        "custom_scan_input",
        "custom_scan_input_origin",
        "documents_root",
        "documents_root_origin",
        "fcx_mode",
        "fcx_mode_origin",
        "formid_databases",
        "formid_databases_origin",
        "formid_value_lookup",
        "formid_value_lookup_origin",
        "game_executable",
        "game_executable_origin",
        "game_root",
        "game_root_origin",
        "game_version_selection",
        "game_version_selection_origin",
        "height",
        "height_origin",
        "ini_folder",
        "ini_folder_origin",
        "managed_game",
        "managed_game_origin",
        "max_concurrent_scans",
        "max_concurrent_scans_origin",
        "maximized",
        "maximized_origin",
        "mods_root",
        "mods_root_origin",
        "move_unsolved_logs",
        "move_unsolved_logs_origin",
        "papyrus_log",
        "papyrus_log_origin",
        "results_panel_width",
        "results_panel_width_origin",
        "show_statistics",
        "show_statistics_origin",
        "simplify_logs",
        "simplify_logs_origin",
        "sort_ascending",
        "sort_ascending_origin",
        "unsolved_logs_destination",
        "unsolved_logs_destination_origin",
        "update_check",
        "update_check_origin",
        "update_source",
        "update_source_origin",
        "width",
        "width_origin",
        "origin",
        "preferences",
        "tui",
        "window_geometry",
        "main_tab",
        "backups_tab",
        "articles_tab",
        "results_tab",
    ),
)

DEFAULTS_PREDICATE = replace(
    DEFAULTS_PROJECTION_PREDICATE,
    id="user-settings.defaults",
    capability_id="user-settings.defaults",
    rust_symbols=("published_defaults",),
    runtime_operations=(
        None,
        "user_settings_gui_published_defaults",
        "publishedUserSettingsDefaults",
        "user_settings_published_defaults",
    ),
)
