"""
Conditional section utilities for report composition.

This module provides utilities for creating report sections with
headers that only appear when content exists.
"""

from collections.abc import Callable

from ClassicLib.rust.report_rust import ReportFragment
from ClassicLib.ScanLog.ReportGenerator import ReportGeneratorFragments


class ConditionalSection:
    """
    ConditionalSection class.

    Provides static methods for generating sections with headers, which are added
    only if corresponding content exists. These methods aim to simplify the process
    of conditionally appending headers to content fragments.

    Methods:
        with_header: Generate a section with a header only if content exists.
        with_custom_header: Generate a section with a custom header fragment only if content exists.
    """

    @staticmethod
    def with_header(
        content_generator: Callable[[], ReportFragment],
        header_text: str | None,
        header_generator: Callable[[], ReportFragment] | None = None,
    ) -> ReportFragment:
        """
        Generate a section with header only if content exists.

        This replaces the pattern of:
        1. Save list length
        2. Call function that might add content
        3. Check if content was added
        4. Retroactively insert header

        Args:
            content_generator: Function that generates the content fragment
            header_text: The header text to prepend if content exists (or None to use header_generator)
            header_generator: Optional custom header generator function

        Returns:
            Combined fragment with header if content exists, or empty fragment
        """
        content = content_generator()

        if content.has_content:
            if header_generator:
                header = header_generator()
            elif header_text:
                header = ReportGeneratorFragments.generate_mod_check_header(header_text)
            else:
                return content
            return header + content

        return content

    @staticmethod
    def with_custom_header(
        content_generator: Callable[[], ReportFragment],
        header_generator: Callable[[], ReportFragment],
    ) -> ReportFragment:
        """
        Creates a `ReportFragment` with a custom header if the content generated by the
        `content_generator` contains data. If no content is present, it skips adding the header.

        Args:
            content_generator (Callable[[], ReportFragment]): Function that generates the main
                content of type `ReportFragment`.
            header_generator (Callable[[], ReportFragment]): Function that generates the custom
                header of type `ReportFragment`.

        Returns:
            ReportFragment: The resulting report fragment which includes the header only if
            the content has data, otherwise returns the content alone.
        """
        content = content_generator()

        if content.has_content:
            header = header_generator()
            return header + content

        return content


def conditional_mod_section(
    detector_func: Callable[[], ReportFragment],
    check_type: str,
) -> ReportFragment:
    """
    Create a mod detection section with conditional header.

    This is a convenience function for the common pattern of:
    - Running a mod detector
    - Adding a header only if mods were detected

    Args:
        detector_func: Function that detects mods and returns a fragment
        check_type: The type of check (e.g., "CONFLICT (TOGETHER)", "FREQUENTLY CRASH")

    Returns:
        Fragment with header if mods detected, or empty fragment
    """
    return ConditionalSection.with_header(detector_func, check_type)
