"""
Report composer for combining multiple fragments.

This module provides the ReportComposer class for composing
multiple report fragments into a complete report.
"""

from collections.abc import Callable

from ClassicLib.ScanLog.composition.conditional_section import ConditionalSection
from ClassicLib.ScanLog.fragments import ReportFragment


class ReportComposer:
    """
    Responsible for managing and composing report fragments into a cohesive structure.

    This class provides functionality to add report fragments, conditionally add sections,
    and compose them into a final report. It allows for method chaining to streamline
    the construction of reports.

    Attributes:
        fragments (list[ReportFragment]): Stores a list of ReportFragment objects.
    """

    def __init__(self) -> None:
        """
        Initializes an instance of the class.

        The constructor sets up the instance by initializing required attributes.
        """
        self.fragments: list[ReportFragment] = []

    def add(self, fragment: ReportFragment) -> "ReportComposer":
        """
        Adds a report fragment to the current collection of fragments.

        This method allows chaining by returning the instance of the class after
        adding the provided fragment to the list of report fragments.

        Args:
            fragment: The report fragment to be added to the collection.

        Returns:
            ReportComposer: The instance of the class, enabling method chaining.
        """
        self.fragments.append(fragment)
        return self

    def add_conditional(
        self,
        content_generator: Callable[[], ReportFragment],
        header_text: str,
    ) -> "ReportComposer":
        """
        Adds a conditional section to the report composer. This method creates a new
        conditional section using the provided content generator and header text, then
        appends it to the report composer fragments. Finally, it returns the updated
        report composer instance.

        Args:
            content_generator (Callable[[], ReportFragment]): A callable that generates
                a `ReportFragment`, which is used to create the conditional section.
            header_text (str): The header text for the conditional section.

        Returns:
            ReportComposer: The updated report composer instance with the added
            conditional section.
        """
        fragment = ConditionalSection.with_header(content_generator, header_text)
        self.fragments.append(fragment)
        return self

    def add_conditional_custom(
        self,
        content_generator: Callable[[], ReportFragment],
        header_generator: Callable[[], ReportFragment],
    ) -> "ReportComposer":
        """
        Adds a conditional custom section with a custom header and body content to the report.

        This method creates a conditional section using the provided content and header generators
        and appends it to the list of report fragments. It then returns the updated report composer
        to allow method chaining.

        Args:
            content_generator (Callable[[], ReportFragment]): A callable function that
                generates the content of the conditional section.
            header_generator (Callable[[], ReportFragment]): A callable function that
                generates the header for the conditional section.

        Returns:
            ReportComposer: The updated instance of the report composer.
        """
        fragment = ConditionalSection.with_custom_header(content_generator, header_generator)
        self.fragments.append(fragment)
        return self

    def compose(self) -> ReportFragment:
        """
        Composes and returns a consolidated ReportFragment from a list of fragments.

        This method iterates through the available fragments and combines them into a
        single, consolidated ReportFragment. If no fragments are present, it returns
        an empty ReportFragment.

        Returns:
            ReportFragment: A consolidated instance of ReportFragment formed by
            combining all individual fragments. Returns an empty ReportFragment if
            no fragments are available.
        """
        if not self.fragments:
            return ReportFragment.empty()

        result = self.fragments[0]
        for fragment in self.fragments[1:]:
            result += fragment

        return result

    def build(self) -> ReportFragment:
        """
        Builds and returns a ReportFragment object.

        This method is responsible for invoking the compose function and returning
        the resulting ReportFragment instance.

        Returns:
            ReportFragment: The resulting report fragment generated by the compose
            function.
        """
        return self.compose()

    def to_list(self) -> list[str]:
        """
        Converts the composed result to a list of strings.

        This method first composes the internal representation and then
        transforms the result into a list of strings.

        Returns:
            list[str]: A list of strings derived from the composed result.
        """
        return self.compose().to_list()
